import net.minecraft.world.World;import net.minecraft.profiler.Profiler;
import java.util.*;import java.io.*;import com.google.gson.*;import net.minecraft.block.Block;import net.minecraft.init.Blocks;import com.miaokatze.gtsr.common.blocks.*;import com.miaokatze.gtsr.common.dimension.prosperity.*;import com.miaokatze.gtsr.common.dimension.prosperity.remaster.*;import com.miaokatze.gtsr.common.dimension.framework.structure.BlockSink;
class EntryApronCheck extends SurfaceArrivalCheck {
 static class W extends SurfaceArrivalCheck.W {
  Map<String,int[]> nativeColumns;
  public Block getBlock(int x,int y,int z){String k=key(x,y,z);if(blocks.containsKey(k))return blocks.get(k);if(nativeColumns==null)nativeColumns=new HashMap<>();String column=x+":"+z;int[] c=nativeColumns.get(column);if(c==null){c=new int[]{ProsperityTerrainProfile.heightAt(seed,x+ax,z+az),ChunkProviderProsperityRuins.naturalWaterTopAt(seed,x+ax,z+az)};nativeColumns.put(column,c);}return y+ay<=c[0]?BlocksGTSR.prosperityStone:y+ay<=c[1]?Blocks.water:Blocks.air;}
 }
 static W wideWorld(RemasterSite s,int[] at,int r)throws Exception {W w=(W)RemasterRuntimeCheck.u.allocateInstance(W.class);w.blocks=new HashMap<>();w.metas=new HashMap<>();w.tiles=new HashMap<>();w.seed=s.seed;w.ax=s.x;w.ay=s.y;w.az=s.z;w.loaded=true;RemasterRuntimeCheck.set(w,World.class,"provider",RemasterRuntimeCheck.u.allocateInstance(WorldProviderProsperityRuins.class));RemasterRuntimeCheck.set(w,World.class,"theProfiler",new Profiler());RemasterRuntimeCheck.set(w,World.class,"rand",new Random(1));BlockSink sink=(x,y,z,b,m,f)->{int xx=x-s.x,zz=z-s.z;if(Math.abs(xx-at[0])>r||Math.abs(zz-at[2])>r)return true;String authored=b.toString()+"#"+m;Block block=b.toString().equals("minecraft:stonebrick")?Blocks.stonebrick:b.toString().equals("minecraft:stone_brick_stairs")?Blocks.stone_brick_stairs:b.toString().equals("minecraft:fence")?Blocks.fence:RemasterRuntime.resolve(authored);if(block==Blocks.stone&&!b.toString().equals("minecraft:stone")){unknown++;throw new AssertionError("unknown production palette "+authored);}String k=w.key(xx,y-s.y,zz);w.blocks.put(k,block);w.metas.put(k,RemasterRuntime.meta(authored));return true;};for(int cx=(s.x+at[0]-r)>>4;cx<=(s.x+at[0]+r)>>4;cx++)for(int cz=(s.z+at[2]-r)>>4;cz<=(s.z+at[2]+r)>>4;cz++){RemasterTerrain.build(s,sink,cx,cz);RemasterWorldgen.geometry(s,s.plan(),sink,cx,cz);}return w;}

 static JsonObject column(W w,int x,int z){JsonObject o=new JsonObject();o.addProperty("x",x);o.addProperty("z",z);o.addProperty("nativeTop",ProsperityTerrainProfile.heightAt(w.seed,w.ax+x,w.az+z));o.addProperty("waterTop",ChunkProviderProsperityRuins.naturalWaterTopAt(w.seed,w.ax+x,w.az+z));JsonArray a=new JsonArray();for(int y=-8;y<=12;y++){String k=w.key(x,y,z);if(!w.blocks.containsKey(k))continue;JsonObject b=new JsonObject();b.addProperty("y",y);b.addProperty("block",w.getBlock(x,y,z).getUnlocalizedName());b.addProperty("meta",w.getBlockMetadata(x,y,z));a.add(b);}o.add("emitted",a);return o;}
 static JsonObject verifyCandidate(JsonObject result,W w,int[] target,Set<String> source,Map<String,Block> original,Map<String,Integer> om){boolean preserved=true;for(String k:source)if(w.blocks.get(k)!=original.get(k)||!Objects.equals(w.metas.get(k),om.get(k)))preserved=false;result.addProperty("sourceVolumeIncludingAirUnchanged",preserved);JsonArray path=result.getAsJsonObject("physical").getAsJsonArray("reverseClosestOrGoalPath");StairCollisionCheck.E e=new StairCollisionCheck.E(w);JsonArray first=path.get(0).getAsJsonArray();e.setPosition(first.get(0).getAsDouble(),first.get(1).getAsDouble(),first.get(2).getAsDouble());boolean reverse=true;for(int k=1;k<path.size();k++){JsonArray a=path.get(k).getAsJsonArray();e.onGround=true;StairCollisionCheck.move(e,a.get(0).getAsDouble(),a.get(2).getAsDouble());for(int j=0;j<12;j++)e.moveEntity(0,-.12,0);if(Math.abs(e.posX-a.get(0).getAsDouble())>.1||Math.abs(e.posZ-a.get(2).getAsDouble())>.1||!StairCollisionCheck.supported(w,e)||!w.getCollidingBoundingBoxes(e,e.boundingBox).isEmpty())reverse=false;}result.addProperty("samePhysicalPathBackwardFullBody",reverse);result.addProperty("entityWidth",.6);result.addProperty("entityHeight",1.8);result.addProperty("stepHeight",.5);return result;}
 static String key(double[] a){return (int)Math.floor(a[0])+":"+(int)Math.floor(a[2])+":"+Math.round(a[1]*2);}
 static JsonObject bilateral(W w,int[] target,int r,int max){JsonObject out=new JsonObject();ArrayDeque<double[]> q=new ArrayDeque<>();Set<String> seen=new HashSet<>();Map<String,String> prev=new HashMap<>();Map<String,double[]> states=new HashMap<>();JsonArray starts=new JsonArray();
 for(int x=target[0]-r;x<=target[0]+r;x++)for(int z=target[2]-r;z<=target[2]+r;z++){if(Math.max(Math.abs(x-target[0]),Math.abs(z-target[2]))!=r)continue;int y=ProsperityTerrainProfile.heightAt(w.seed,w.ax+x,w.az+z)-w.ay+1;StairCollisionCheck.E e=new StairCollisionCheck.E(w);e.setPosition(x+.5,y,z+.5);boolean emitted=w.blocks.containsKey(w.key(x,y-1,z)),clear=w.getCollidingBoundingBoxes(e,e.boundingBox).isEmpty(),support=StairCollisionCheck.supported(w,e);JsonObject c=new JsonObject();c.add("at",gson.toJsonTree(new int[]{x,y,z}));c.addProperty("emittedFloor",emitted);c.addProperty("clear",clear);c.addProperty("supported",support);starts.add(c);if(!emitted&&clear&&support){double[] a={x+.5,y,z+.5};q.add(a);String k=key(a);prev.put(k,null);states.put(k,a);}}
 int count=q.size(),budget=max;String closestKey=null,goal=null;double closest=999;while(!q.isEmpty()&&budget-->0){double[] a=q.remove();String k=key(a);if(!seen.add(k))continue;int xx=(int)Math.floor(a[0]),zz=(int)Math.floor(a[2]);double dist=Math.abs(xx-target[0])+Math.abs(zz-target[2])+Math.abs(a[1]-target[1]-1);if(dist<closest){closest=dist;closestKey=k;}if(xx==target[0]&&zz==target[2]&&a[1]>=target[1]+.5&&a[1]<=target[1]+1.01){goal=k;break;}for(int[] d:new int[][]{{1,0},{-1,0},{0,1},{0,-1}}){double x=a[0]+d[0],z=a[2]+d[1];if(Math.abs(x-.5-target[0])>r||Math.abs(z-.5-target[2])>r)continue;StairCollisionCheck.E e=new StairCollisionCheck.E(w);e.setPosition(a[0],a[1],a[2]);e.onGround=true;StairCollisionCheck.move(e,x,z);for(int i=0;i<12;i++)e.moveEntity(0,-.12,0);if(Math.abs(e.posX-x)>.1||Math.abs(e.posZ-z)>.1||!StairCollisionCheck.supported(w,e)||!w.getCollidingBoundingBoxes(e,e.boundingBox).isEmpty())continue;double[] b={e.posX,e.boundingBox.minY,e.posZ};StairCollisionCheck.E back=new StairCollisionCheck.E(w);back.setPosition(b[0],b[1],b[2]);back.onGround=true;StairCollisionCheck.move(back,a[0],a[2]);for(int v=0;v<12;v++)back.moveEntity(0,-.12,0);if(Math.abs(back.posX-a[0])>.1||Math.abs(back.posZ-a[2])>.1||Math.abs(back.boundingBox.minY-a[1])>.05||!StairCollisionCheck.supported(w,back)||!w.getCollidingBoundingBoxes(back,back.boundingBox).isEmpty())continue;String kk=key(b);if(!prev.containsKey(kk)){prev.put(kk,k);states.put(kk,b);}q.add(b);}}
 out.addProperty("radius",r);out.addProperty("walked",goal!=null);out.addProperty("naturalStarts",count);out.addProperty("visited",seen.size());out.addProperty("closestL1",closest);out.addProperty("budgetRemaining",budget);out.add("ring",starts);JsonArray path=new JsonArray();String p=goal==null?closestKey:goal;while(p!=null){path.add(gson.toJsonTree(states.get(p)));p=prev.get(p);}out.add("reverseClosestOrGoalPath",path);JsonArray nearby=new JsonArray();for(String k:seen){double[] a=states.get(k);if(Math.abs(a[0]-.5-target[0])+Math.abs(a[2]-.5-target[2])<=10)nearby.add(gson.toJsonTree(a));}out.add("nearbyVisited",nearby);JsonArray attempts=new JsonArray();if(closestKey!=null){double[] a=states.get(closestKey);out.add("closestState",gson.toJsonTree(a));for(int[] d:new int[][]{{1,0},{-1,0},{0,1},{0,-1}}){StairCollisionCheck.E e=new StairCollisionCheck.E(w);e.setPosition(a[0],a[1],a[2]);e.onGround=true;StairCollisionCheck.move(e,a[0]+d[0],a[2]+d[1]);for(int i=0;i<12;i++)e.moveEntity(0,-.12,0);JsonObject j=new JsonObject();j.add("direction",gson.toJsonTree(d));j.add("result",gson.toJsonTree(new double[]{e.posX,e.boundingBox.minY,e.posZ}));j.add("column",column(w,(int)Math.floor(a[0])+d[0],(int)Math.floor(a[2])+d[1]));attempts.add(j);}}out.add("closestMoveAttempts",attempts);return out;}


 static boolean continuous(W w,JsonObject physical,boolean reversed){JsonArray path=physical.getAsJsonArray("reverseClosestOrGoalPath");if(!physical.get("walked").getAsBoolean()||path.size()==0)return false;StairCollisionCheck.E player=new StairCollisionCheck.E(w);int start=reversed?0:path.size()-1,step=reversed?1:-1;JsonArray first=path.get(start).getAsJsonArray();player.setPosition(first.get(0).getAsDouble(),first.get(1).getAsDouble(),first.get(2).getAsDouble());for(int i=start+step;i>=0&&i<path.size();i+=step){JsonArray a=path.get(i).getAsJsonArray();player.onGround=true;StairCollisionCheck.move(player,a.get(0).getAsDouble(),a.get(2).getAsDouble());for(int j=0;j<12;j++)player.moveEntity(0,-.12,0);if(Math.abs(player.posX-a.get(0).getAsDouble())>.1||Math.abs(player.posZ-a.get(2).getAsDouble())>.1||Math.abs(player.boundingBox.minY-a.get(1).getAsDouble())>.05||!StairCollisionCheck.supported(w,player)||!w.getCollidingBoundingBoxes(player,player.boundingBox).isEmpty())return false;}return true;}
 static JsonObject contracts(RemasterSite old,RemasterSite s)throws Exception {
  JsonObject out=new JsonObject();int[] initial=s.entryApronWrites();int[] exported=s.entryApronWrites();if(exported.length>0)exported[0]++;
  if(!Arrays.equals(initial,s.entryApronWrites()))throw new AssertionError("getter alias");
  net.minecraft.nbt.NBTTagCompound saved=s.save();int[] alias=saved.getIntArray("entryApronWrites");if(alias.length>0)alias[0]++;
  if(!Arrays.equals(initial,s.entryApronWrites()))throw new AssertionError("NBT save alias");
  RemasterSite read=RemasterSite.read(s.save());if(!Arrays.equals(initial,read.entryApronWrites())||!read.id().equals(old.id())||read.y!=old.y)throw new AssertionError("NBT identity");
  if(RemasterSite.read(old.save()).entryApronVersion!=0)throw new AssertionError("legacy migration");
  TreeMap<String,String> forward=new TreeMap<>(),reverse=new TreeMap<>();List<int[]> chunks=new ArrayList<>();
  for(int cx=s.minX()>>4;cx<=s.maxX()>>4;cx++)for(int cz=s.minZ()>>4;cz<=s.maxZ()>>4;cz++)chunks.add(new int[]{cx,cz});
  for(int pass=0;pass<2;pass++){final Map<String,String> collected=pass==0?forward:reverse;if(pass==1)Collections.reverse(chunks);
   for(int[] c:chunks){final int cx=c[0],cz=c[1];BlockSink sink=(x,y,z,b,m,f)->{if((x>>4)!=cx||(z>>4)!=cz||x<s.minX()||x>s.maxX()||z<s.minZ()||z>s.maxZ())throw new AssertionError("foreign owner");String k=x+":"+y+":"+z;if(collected.put(k,b+"#"+m)!=null)throw new AssertionError("duplicate owner write");return true;};RemasterEntryApron.geometry(pass==0?s:read,s.plan(),sink,cx,cz);}}
  if(!forward.equals(reverse)||forward.size()!=initial.length/5)throw new AssertionError("chunk/NBT order drift");
  final int[] rejectedCalls={0};BlockSink reject=(x,y,z,b,m,f)->{rejectedCalls[0]++;return true;};
  List<RemasterSite> bad=new ArrayList<>();bad.add(new RemasterSite(s.prefab,s.variant,s.seed,s.x,s.y,s.z,s.layout,s.roadVersion,s.entryApronVersion,"invalid",initial));
  if(initial.length>0){int[] duplicate=Arrays.copyOf(initial,initial.length+5);System.arraycopy(initial,0,duplicate,initial.length,5);bad.add(new RemasterSite(s.prefab,s.variant,s.seed,s.x,s.y,s.z,s.layout,s.roadVersion,s.entryApronVersion,s.entryApronSha,duplicate));int[] meta=initial.clone();meta[4]=15;bad.add(new RemasterSite(s.prefab,s.variant,s.seed,s.x,s.y,s.z,s.layout,s.roadVersion,s.entryApronVersion,s.entryApronSha,meta));}
  for(RemasterSite b:bad){if(RemasterEntryApron.valid(b,b.plan()))throw new AssertionError("bad plan accepted");RemasterWorldgen.geometry(b,b.plan(),reject,b.minX()>>4,b.minZ()>>4);}
  if(rejectedCalls[0]!=0)throw new AssertionError("source written before plan rejection");
  out.addProperty("getterAndNbtNoAlias",true);out.addProperty("sameIdentitySavedY",true);out.addProperty("legacyMissingFieldsNoPlan",true);out.addProperty("ownerOrderStable",true);out.addProperty("ownerWrites",forward.size());out.addProperty("invalidPlansZeroWrites",true);out.addProperty("sourceSHA",s.entryApronSha);return out;
 }
 public static void main(String[] args)throws Exception { NativeTerrainFixture.initialize();
  StairCollisionCheck.main(new String[0]);BlocksGTSR.prosperityStone=new BlockProsperityStone("ProsperityStone","gtsr:prosperity_stone");
  java.lang.reflect.Field rf=RemasterBlocks.class.getDeclaredField("REGISTRY");rf.setAccessible(true);Map reg=(Map)rf.get(null);for(java.lang.reflect.Method m:RemasterBlocks.class.getDeclaredMethods())if(m.getName().matches("block[0-9]+")){m.setAccessible(true);RemasterBlock b=(RemasterBlock)m.invoke(null);reg.put(b.id(),b);}com.miaokatze.gtsr.common.dimension.prosperity.encounter.ForgottenLakeEncounterRegistry.sealedChest=new com.miaokatze.gtsr.common.dimension.prosperity.encounter.BlockSealedChest();
  RemasterRuntimeCheck.setBlock("stonebrick",new net.minecraft.block.BlockStoneBrick());java.lang.reflect.Constructor<net.minecraft.block.BlockStairs> stair=net.minecraft.block.BlockStairs.class.getDeclaredConstructor(Block.class,int.class);stair.setAccessible(true);RemasterRuntimeCheck.setBlock("stone_brick_stairs",stair.newInstance(Blocks.stonebrick,0));RemasterRuntimeCheck.setBlock("fence",new net.minecraft.block.BlockFence("planks",net.minecraft.block.material.Material.wood));
  java.lang.reflect.Constructor<net.minecraft.block.BlockStaticLiquid> waterConstructor=net.minecraft.block.BlockStaticLiquid.class.getDeclaredConstructor(net.minecraft.block.material.Material.class);waterConstructor.setAccessible(true);RemasterRuntimeCheck.setBlock("water",waterConstructor.newInstance(net.minecraft.block.material.Material.water));


 JsonArray all=new JsonArray();String[] ids={"archivist_kiosk","weighbridge","resonant_station"};int[] vs={1,0,2};int[][] anchors={{-648,83,-1487},{-1968,78,81},{-1307,103,4860}},ts={{35,2,1},{35,2,1},{114,3,7}};
 for(int i=0;i<3;i++) {RemasterSite old=new RemasterSite(ids[i],vs[i],20261001L,anchors[i][0],anchors[i][1],anchors[i][2],"ordinary");RemasterSite fresh=RemasterEntryApron.admit(old);JsonObject r=new JsonObject();r.addProperty("id",ids[i]);r.addProperty("planAccepted",fresh!=null);r.addProperty("oldVersion",RemasterSite.read(old.save()).entryApronVersion);System.out.println(ids[i]+" plan="+(fresh==null?"REJECT":fresh.entryApronWrites().length/5));
 if(fresh!=null){RemasterSite restored=RemasterSite.read(fresh.save());if(!restored.id().equals(old.id())||restored.y!=old.y||!Arrays.equals(restored.entryApronWrites(),fresh.entryApronWrites()))throw new AssertionError("NBT identity/plan"); W original=wideWorld(old,ts[i],12),w=wideWorld(restored,ts[i],12);JsonArray ev=new JsonArray();for(String k:original.blocks.keySet()){String[] parts=k.split(":");if(parts.length!=3)parts=k.split(",");JsonObject v=new JsonObject();v.add("at",gson.toJsonTree(new int[]{Integer.parseInt(parts[0]),Integer.parseInt(parts[1]),Integer.parseInt(parts[2])}));v.addProperty("block",original.blocks.get(k)==Blocks.air?"minecraft:air":"solid");v.addProperty("meta",original.metas.get(k));ev.add(v);}
 r.add("oldStrict8",probe(original,ts[i]));r.add("strict8",probe(w,ts[i]));r.add("physical",bilateral(w,ts[i],8,3000));r=verifyCandidate(r,w,ts[i],original.blocks.keySet(),original.blocks,original.metas);r.addProperty("sourcePreserved",r.get("sourceVolumeIncludingAirUnchanged").getAsBoolean()); r.add("writes",gson.toJsonTree(restored.entryApronWrites()));r.addProperty("samePhysicalPathForwardFullBody",continuous(w,r.getAsJsonObject("physical"),false));r.add("contracts",contracts(old,restored));r.addProperty("nbtStable",true);}
 all.add(r); }
 JsonArray variants=new JsonArray();int failed=0,total=0,falseAccepts=0; if(!Arrays.asList(args).contains("--fixed-only")) {
 java.lang.reflect.Method anchor=RemasterPlanner.class.getDeclaredMethod("anchor",String.class,long.class,long.class,int.class,int.class);anchor.setAccessible(true);
 for(JsonElement de:RemasterCatalog.config().getAsJsonArray("prefabs")){JsonObject desc=de.getAsJsonObject();JsonObject placement=desc.getAsJsonObject("placement");if(desc.get("id").getAsString().startsWith("city_"))continue;if(placement==null||!placement.has("entryApronEnvelope"))continue;total++;String id=desc.get("id").getAsString();int variant=desc.get("variant").getAsInt();RemasterSite chosen=null;JsonObject chosenForward=null,chosenPhysical=null;boolean sourcePreserved=false;int attempt=0,pureRejected=0;
 for(;attempt<96;attempt++){RemasterSite base=(RemasterSite)anchor.invoke(null,id,20261001L,((long)variant)<<12, -6000+attempt*113+total*23, -7000+attempt*37+total*109);if(base==null){pureRejected++;continue;}RemasterSite admitted=RemasterEntryApron.admit(base);if(admitted==null){pureRejected++;continue;}int[] target=StairCollisionCheck.point(placement.getAsJsonObject("entryApronEnvelope").getAsJsonArray("entry"));W w=wideWorld(admitted,target,12);JsonObject probeResult=probe(w,target),physical=bilateral(w,target,8,3000);if(probeResult.get("walked").getAsBoolean()&&physical.get("walked").getAsBoolean()&&continuous(w,physical,false)&&continuous(w,physical,true)){physical.addProperty("continuousForward",true);physical.addProperty("continuousBackward",true);W baseline=wideWorld(base,target,12);sourcePreserved=true;for(String cell:baseline.blocks.keySet())if(w.blocks.get(cell)!=baseline.blocks.get(cell)||!Objects.equals(w.metas.get(cell),baseline.metas.get(cell)))sourcePreserved=false;if(!sourcePreserved)throw new AssertionError("source or pre-existing geometry changed "+id+":"+variant);chosen=admitted;chosenForward=probeResult;chosenPhysical=physical;break;}falseAccepts++;System.out.println("FALSE_ACCEPT "+id+":"+variant+" attempt="+attempt);}
 JsonObject row=new JsonObject();row.addProperty("id",id);row.addProperty("variant",variant);row.addProperty("attempt",attempt);row.addProperty("pureRejected",pureRejected);row.addProperty("sourceSHA",desc.get("sourceSha256").getAsString());row.addProperty("pass",chosen!=null);if(chosen!=null){row.addProperty("x",chosen.x);row.addProperty("y",chosen.y);row.addProperty("z",chosen.z);row.addProperty("writes",chosen.entryApronWrites().length/5);row.addProperty("sourcePreserved",sourcePreserved);row.add("strict8",chosenForward);row.add("bilateralMC",chosenPhysical);}else failed++;variants.add(row);try(Writer interim=new FileWriter(new File(System.getProperty("gtsr.entry.output","temp/entry-apron-exec"),"variants.json"))){gson.toJson(variants,interim);}System.out.println("VARIANT "+total+" "+id+":"+variant+" "+(chosen!=null));}
 } try(Writer wr=new FileWriter(new File(System.getProperty("gtsr.entry.output","temp/entry-apron-exec"),"variants.json"))){gson.toJson(variants,wr);}System.out.println("VARIANTS total="+total+" failed="+failed);
 try(Writer wr=new FileWriter(new File(System.getProperty("gtsr.entry.output","temp/entry-apron-exec"),"results.json"))){gson.toJson(all,wr);}if(failed>0||falseAccepts>0)throw new AssertionError("failed="+failed+" falseAccept="+falseAccepts);for(JsonElement item:all){JsonObject r=item.getAsJsonObject();if(!r.get("planAccepted").getAsBoolean()||!r.getAsJsonObject("strict8").get("walked").getAsBoolean()||!r.getAsJsonObject("physical").get("walked").getAsBoolean()||!r.get("samePhysicalPathBackwardFullBody").getAsBoolean()||!r.get("samePhysicalPathForwardFullBody").getAsBoolean()||!r.get("sourcePreserved").getAsBoolean())throw new AssertionError("fixed case failed "+r.get("id"));} }
}