'use strict';
/* Read-only design verification. CLI: node tools/prosperity/future_design_verify.cjs model.json [...]
 * JS clients: const {verify,loadMaterials}=require(...); verify(model,{materials}).
 * AIR is an authored cell, never inferred from a missing voxel. Runtime registration is not implied.
 */
const fs=require('fs'),path=require('path'),vm=require('vm');
const ROOT=path.resolve(__dirname,'../..');
const Kit=require(path.join(ROOT,'plan/prosperity/future-design/voxel-kit.js'));
const Renderer=require(path.join(ROOT,'plan/prosperity/renderer.js'));
const AIR=Kit.palette.air,key=p=>p.join(','),entityRoles=new Set(['boss','elite','mob','guard','entity']);
let cachedMaterials;
function loadMaterials(){if(cachedMaterials)return cachedMaterials;const context={window:{}};vm.createContext(context);for(const name of ['textures/textures.js','textures/remaster.js'])vm.runInContext(fs.readFileSync(path.join(ROOT,'plan/prosperity',name),'utf8'),context,{filename:name});return cachedMaterials=context.window.PROSPERITY_TEXTURES;}
function verify(model,{materials=loadMaterials()}={}){
 const errors=[],warnings=[],checks={materialCells:0,roofCells:0,reservedAirCells:0,entityAABBs:0,interactiveNodes:0,routeSamples:0,stairSamples:0,viewpoints:0};
 const fail=s=>{if(errors.length<150)errors.push(s);},size=model.size||[],voxels=model.voxels||[],cells=new Map(),shapeCache=new Map();
 const inside=p=>p.length===3&&p.every((v,i)=>Number.isFinite(v)&&v>=0&&v<size[i]);
 if(size.length!==3||!size.every(v=>Number.isInteger(v)&&v>0))fail('invalid entry size');
 if(model.designOnly!==true||model.implemented!==false)fail('model must be designOnly:true / implemented:false');
 if(model.entrySource?.catalogId!==model.id||model.stableEntryId!==model.id)fail('stable catalog identity missing or mismatched');
 for(const v of voxels){const p=v.slice(0,3),k=key(p);if(!inside(p)||!p.every(Number.isInteger))fail('voxel outside entry bounds '+k);if(cells.has(k))fail('duplicate voxel '+k);cells.set(k,v);try{Kit.material(v[3]);}catch(e){fail(e.message);}if(v[3]!==AIR){checks.materialCells++;const m=materials[v[3]];if(!m||!m.texture&&!m.faces)fail('unresolved material '+v[3]);}}
 const at=p=>cells.get(key(p))?.[3],solid=p=>!!at(p)&&at(p)!==AIR;
 function boxes(m){if(shapeCache.has(m))return shapeCache.get(m);if(m===AIR)return[];const mat=materials[m]||{},faces=Renderer.shape(mat),result=[];for(let i=0;i+5<faces.length;i+=6){const ps=faces.slice(i,i+6).flatMap(f=>f.p),lo=[0,1,2].map(c=>Math.min(...ps.map(p=>p[c]))),hi=[0,1,2].map(c=>Math.max(...ps.map(p=>p[c])));if(hi.every((v,c)=>v>lo[c]))result.push([lo,hi]);}if(!result.length&&faces.length)result.push([[0,0,0],[1,1,1]]);shapeCache.set(m,result);return result;}
 function collision(lo,hi,explicit=false){for(let x=Math.floor(lo[0]);x<Math.ceil(hi[0]-1e-8);x++)for(let y=Math.floor(lo[1]);y<Math.ceil(hi[1]-1e-8);y++)for(let z=Math.floor(lo[2]);z<Math.ceil(hi[2]-1e-8);z++){const p=[x,y,z],m=at(p);if(explicit&&!m)return 'unspecified AIR '+key(p);if(!m||m===AIR)continue;for(const [a,b]of boxes(m))if(a.every((v,c)=>v+p[c]<hi[c]-1e-7&&b[c]+p[c]>lo[c]+1e-7))return 'blocked by '+m+' at '+key(p);}return null;}
 function support(x,y,z){const yy=Math.floor(y-1e-6),p=[Math.floor(x),yy,Math.floor(z)],m=at(p);if(!m||m===AIR)return false;return boxes(m).some(([a,b])=>Math.abs(p[1]+b[1]-y)<1e-5&&x>=p[0]+a[0]-1e-6&&x<=p[0]+b[0]+1e-6&&z>=p[2]+a[2]-1e-6&&z<=p[2]+b[2]+1e-6);}
 function stance(p,label,stepAllowance=0){if(!inside(p)){fail(label+' outside bounds');return;}if(!support(...p))fail(label+' no solid foot support '+p);const c=collision([p[0]-.3,p[1]+stepAllowance,p[2]-.3],[p[0]+.3,p[1]+1.8,p[2]+.3],true);if(c)fail(label+' '+c);}
 function los(a,b,skip){const distance=Math.hypot(...a.map((v,i)=>v-b[i])),steps=Math.ceil(distance*10);for(let i=1;i<steps;i++){const p=a.map((v,c)=>v+(b[c]-v)*i/steps),cell=p.map(Math.floor);if(key(cell)===skip)continue;if(collision(p.map(v=>v-.0001),p.map(v=>v+.0001)))return false;}return true;}
 const roofAllowed=new Set(['gtsr:draft_roof_tile','gtsr:ruins_rust_riveted_plate','gtsr:ruins_slag_masonry']);
 for(const k of model.roofKeys||[]){const v=cells.get(k);if(!v||v[3]===AIR)fail('roofKey missing/air '+k);else if(!roofAllowed.has(v[3].split('#')[0]))fail('roofKey tags non-roof material '+k+' '+v[3]);else checks.roofCells++;}
 if(new Set(model.roofKeys||[]).size!==(model.roofKeys||[]).length)fail('duplicate roof keys');
 for(const box of model.airBoxes||[]){if(!inside(box.min||[])||!inside(box.max||[])||box.min.some((v,i)=>v>box.max[i])){fail('invalid airBox '+box.purpose);continue;}if(box.reserve)for(let x=box.min[0];x<=box.max[0];x++)for(let y=box.min[1];y<=box.max[1];y++)for(let z=box.min[2];z<=box.max[2];z++){checks.reservedAirCells++;if(at([x,y,z])!==AIR)fail('reserved AIR overwritten '+box.purpose+' '+key([x,y,z]));}}
 for(const room of model.rooms||[]){if(!inside(room.min||[])||!inside(room.max||[]))fail('room outside entry '+room.name);if(room.max[1]-room.min[1]<3)fail('room lacks 2-high interior '+room.name);let open=0;for(let x=room.min[0]+1;x<room.max[0];x++)for(let z=room.min[2]+1;z<room.max[2];z++)if(at([x,room.min[1]+1,z])===AIR&&at([x,room.min[1]+2,z])===AIR&&solid([x,room.min[1],z]))open++;if(!open)fail('room has no supported 2-high net space '+room.name);}
 const nodeList=model.nodes||[],entityNodes=nodeList.filter(n=>entityRoles.has(n.role));
 for(let i=0;i<entityNodes.length;i++)for(let j=i+1;j<entityNodes.length;j++){const a=entityNodes[i].entityAABB,b=entityNodes[j].entityAABB;if(a&&b&&a.min.every((v,c)=>v<b.max[c]-1e-7&&a.max[c]>b.min[c]+1e-7))fail('entity AABBs overlap '+entityNodes[i].id+' / '+entityNodes[j].id);}
 const ids=new Set(),nodeCells=new Set();for(const n of nodeList){if(ids.has(n.id))fail('duplicate node '+n.id);ids.add(n.id);if(!n.id||!n.label||!n.role||!inside([n.x,n.y,n.z]))fail('invalid node '+n.id);
  if(entityRoles.has(n.role)){checks.entityAABBs++;if(!n.code||!n.futureIdentity||n.implemented!==false)fail('entity must retain future design identity '+n.id);const a=n.entityAABB;if(!a||!n.size||!a.min.every(Number.isFinite)||!a.max.every(Number.isFinite)){fail('entity AABB missing '+n.id);continue;}if(!inside(a.min)||a.max.some((v,i)=>v>size[i]))fail('entity AABB outside entry '+n.id);const expected=[n.x+.5,n.y,n.z+.5];for(let i=0;i<3;i++)if(Math.abs(a.max[i]-a.min[i]-n.size[i])>1e-5||Math.abs(a.min[i]-(expected[i]-(i===1?0:n.size[i]/2)))>1e-5)fail('entity AABB differs from declared size '+n.id);const c=collision(a.min,a.max,true);if(c)fail('entity '+n.id+' '+c);for(let x=Math.floor(a.min[0]);x<Math.ceil(a.max[0]);x++)for(let z=Math.floor(a.min[2]);z<Math.ceil(a.max[2]);z++)if(!support(Math.max(x+.001,a.min[0]+.001),n.y,Math.max(z+.001,a.min[2]+.001)))fail('entity footprint unsupported '+n.id+' '+x+','+z);
  }else{checks.interactiveNodes++;const nk=key([n.x,n.y,n.z]);if(nodeCells.has(nk))fail('interactive nodes share a block '+n.id);nodeCells.add(nk);if(!support(n.x+.5,n.y,n.z+.5)||!solid([n.x,n.y,n.z]))fail('node lacks tangible block and foot support '+n.id);if(n.role==='chest'&&at([n.x,n.y,n.z])!==Kit.palette.chest)fail('chest is not registered SealedChest#2 '+n.id);if(n.role==='spawner'){const expected={fragile:Kit.palette.spawnerFragile,stable:Kit.palette.spawnerStable,runaway:Kit.palette.spawnerRunaway}[n.type];if(!expected||at([n.x,n.y,n.z])!==expected)fail('spawner registration/type mismatch '+n.id);}if(!n.approach){fail('node missing approach '+n.id);continue;}const p=[n.approach[0]+.5,n.approach[1],n.approach[2]+.5];stance(p,'node '+n.id+' approach');if(Math.hypot(n.approach[0]-n.x,n.approach[2]-n.z)>4.5)fail('node approach beyond interaction reach '+n.id);if(!los(n.interactionEye||[p[0],p[1]+1.62,p[2]],n.interactionTarget||[n.x+.5,n.y+.5,n.z+.5],key([n.x,n.y,n.z])))fail('node interaction LOS blocked '+n.id);}
 }
 for(let ri=0;ri<(model.routes||[]).length;ri++){const points=model.routes[ri],detail=model.routeDetails?.[ri]||{},label='route '+(detail.id||ri);if(points.length<2){fail(label+' needs points');continue;}for(let i=1;i<points.length;i++){const a=points[i-1],b=points[i];if(!a.every(Number.isFinite)||!b.every(Number.isFinite)){fail(label+' nonfinite');continue;}if(!detail.feet&&a[1]!==b[1]){fail(label+' sloped floor-cell route requires explicit stair feet samples');continue;}if(detail.feet&&(!support(...a)||!support(...b)))fail(label+' explicit feet waypoint lacks exact support');const n=Math.max(1,Math.ceil(Math.hypot(...a.map((v,c)=>b[c]-v))*4));let previousY=null;for(let j=0;j<=n;j++){const q=a.map((v,c)=>v+(b[c]-v)*j/n);if(!detail.feet){q[0]+=.5;q[1]+=1;q[2]+=.5;}else{const candidates=[];for(let y=Math.floor(q[1])-1;y<=Math.ceil(q[1]);y++){const p=[Math.floor(q[0]),y,Math.floor(q[2])],m=at(p);if(m&&m!==AIR)for(const[,hi]of boxes(m)){const top=y+hi[1];if(Math.abs(top-q[1])<=.500001&&support(q[0],top,q[2]))candidates.push(top);}}candidates.sort((x,y)=>Math.abs(x-q[1])-Math.abs(y-q[1]));if(candidates.length)q[1]=candidates[0];if(previousY!=null&&Math.abs(q[1]-previousY)>.500001)fail(label+' real tread transition exceeds 0.5');previousY=q[1];}checks.routeSamples++;stance(q,label,detail.feet?.5:0);}}
 }
 for(const f of model.stairFlights||[]){if(f.halfStep!==.5||f.meta!=={east:0,west:1,south:2,north:3}[f.direction])fail('stair direction/meta/half-step mismatch');for(let i=0;i<(f.samples||[]).length;i++){const p=f.samples[i];checks.stairSamples++;stance(p,'stair '+f.direction+' sample '+i,.5);if(i&&Math.abs(p[1]-f.samples[i-1][1])>.500001)fail('stair tread rise exceeds 0.5');}}
 for(const v of model.playerReviewViews||model.viewpoints||[]){checks.viewpoints++;if(![v.eye,v.target].every(p=>p?.length===3&&p.every(Number.isFinite))){fail('invalid viewpoint '+v.label);continue;}if(Math.hypot(...v.eye.map((p,i)=>p-v.target[i]))<.001)fail('zero camera direction '+v.label);stance([v.eye[0],v.eye[1]-1.62,v.eye[2]],'view '+v.label);}
 const counts={id:model.id,category:model.category,size,voxels:voxels.length,solidVoxels:voxels.filter(v=>v[3]!==AIR).length,explicitAirVoxels:voxels.filter(v=>v[3]===AIR).length,materials:new Set(voxels.map(v=>v[3])).size,rooms:(model.rooms||[]).length,nodes:(model.nodes||[]).length,nodeRoles:Object.fromEntries([...new Set((model.nodes||[]).map(n=>n.role))].map(role=>[role,model.nodes.filter(n=>n.role===role).length])),roofKeys:(model.roofKeys||[]).length,routes:(model.routes||[]).length,viewpoints:(model.viewpoints||[]).length};
 return {ok:!errors.length,errors,warnings,counts,checks};
}
module.exports={verify,loadMaterials};
if(require.main===module){const files=process.argv.slice(2);if(!files.length){console.error('Usage: node tools/prosperity/future_design_verify.cjs model.json [...]');process.exitCode=2;}else{const results=[];for(const file of files){const data=JSON.parse(fs.readFileSync(file,'utf8'));for(const model of Array.isArray(data)?data:data.models||[data])results.push(verify(model));}console.log(JSON.stringify({ok:results.every(r=>r.ok),models:results.length,results},null,2));if(results.some(r=>!r.ok))process.exitCode=1;}}
