'use strict';
// Repair stale observation evidence without moving a node or changing geometry.
const fs=require('fs'),path=require('path'),vm=require('vm'),crypto=require('crypto');
const root=path.resolve(__dirname,'../..'),baseline=JSON.parse(fs.readFileSync(path.join(root,'tools/prosperity/profiles/stair-route-baseline.json')));
const apply=process.argv[2]==='apply',key=p=>p.join(','),sha=b=>crypto.createHash('sha256').update(b).digest('hex');
const solid=m=>!!m&&!/stairs|railing|baluster|grate|pipe|valve|chair|bed_frame|pollution|tendril|slab|window|rubble|bracket|lamp|notice|seal_chest|index_frame|flow_window|phase_lens|workbench|cargo|drawer|ledger|oil_drum|coal_bin|filter_bed|ProsperityZenithLog|ProsperityJadeLeaves|roof/.test(m)&&!/(water|lava)#/.test(m);
function ray(cells,eye,target){const p=eye.map(Math.floor),end=target.map(Math.floor),dir=target.map((v,i)=>v-eye[i]),step=dir.map(Math.sign),delta=dir.map(v=>v?Math.abs(1/v):Infinity),next=dir.map((v,i)=>v?((step[i]>0?p[i]+1:p[i])-eye[i])/v:Infinity);for(let guard=0;guard<512;guard++){if(key(p)===key(end))return true;const mat=cells.get(key(p));if(mat&&!/(water|lava)#/.test(mat))return false;const t=Math.min(...next);if(t>1)return true;for(let i=0;i<3;i++)if(Math.abs(next[i]-t)<1e-10){p[i]+=step[i];next[i]+=delta[i];}}return false;}
const rows=[];
for(const variant of [0,1]){const entry=baseline.rows.find(r=>r.id==='subsided_factory'&&r.variant===variant),file=path.join(root,entry.file),before=fs.readFileSync(file),w={window:{}};vm.createContext(w);vm.runInContext(before.toString('utf8'),w);const d=Object.values(w.window.REMASTER_PREFAB7_DATA)[0],m=d.metadata,cells=new Map();for(const[x,y,z,n,i]of d.voxel.runs)for(let j=0;j<n;j++)cells.set(key([x+j,y,z]),d.voxel.palette[i]);const changes=[];
 for(const id of variant===0?['loot7-63']:['loot7-41','loot7-63','loot7-99']){const n=m.nodes.find(n=>n.id===id),index=m.interactionApproaches.findIndex(a=>a.node===id),old=m.interactionApproaches[index],target=[n.x+.5,n.y+.5,n.z+.5];if(ray(cells,old.eye,target))continue;const room=(m.rooms||[]).find(r=>n.x>r.x&&n.x<r.x+r.w-1&&n.z>r.z&&n.z<r.z+r.d-1&&n.y>=r.y&&n.y<=r.y+r.h);let proof;
  outer:for(let r=1;r<=7;r++)for(const[dx,dz]of [[r,0],[-r,0],[0,r],[0,-r],[r,r],[-r,-r],[r,-r],[-r,r]])for(const dy of [0,-1,1,-2,2]){const feet=[n.x+dx,n.y+dy,n.z+dz],floor=[feet[0],feet[1]-1,feet[2]];if(room&&(feet[0]<=room.x||feet[0]>=room.x+room.w-1||feet[2]<=room.z||feet[2]>=room.z+room.d-1))continue;if(!solid(cells.get(key(floor)))||cells.has(key(feet))||cells.has(key([feet[0],feet[1]+1,feet[2]])))continue;const eye=[feet[0]+.5,feet[1]+1.62,feet[2]+.5],distance=Math.hypot(...eye.map((v,i)=>v-target[i]));if(distance<=8&&ray(cells,eye,target)){proof={...old,feet,eye,target,floor:{at:floor,material:cells.get(key(floor))},distance,headClearance:true,rayUnobstructed:true};break outer;}}
  if(!proof)throw Error('No existing-floor visible approach '+variant+'/'+id);m.interactionApproaches[index]=proof;for(const v of m.playerReviewViews||[])if(v.targetId===id){v.eye=proof.eye;v.target=proof.target;v.floor=proof.floor;v.headClearance={feet:proof.feet,head:[proof.feet[0],proof.feet[1]+1,proof.feet[2]],clear:true};v.lineOfSight='clear';}changes.push({node:id,before:old,after:proof,geometryChanges:0,reason:'Existing room floor observation avoids retained resin casing / salt bloom'});
 }
 if(apply&&changes.length)fs.writeFileSync(file,'window.REMASTER_PREFAB7_DATA=window.REMASTER_PREFAB7_DATA||{};window.REMASTER_PREFAB7_DATA['+JSON.stringify(m.id+'-v'+m.variant)+']='+JSON.stringify(d)+';');rows.push({file:entry.file,beforeSHA256:sha(before),afterSHA256:sha(fs.readFileSync(file)),changes});
}
fs.writeFileSync(path.join(root,'plan/implementation/20261002212217/stair-interaction-proofs-'+(apply?'apply':'dry')+'.json'),JSON.stringify({apply,rows},null,2));console.log(JSON.stringify({apply,changes:rows.reduce((n,r)=>n+r.changes.length,0),geometryChanges:0}));
