/* Local authoring repair. Production placement is deliberately handled by the converter. */
'use strict';
const fs=require('fs'),path=require('path'),vm=require('vm'),crypto=require('crypto');
const root=path.resolve(__dirname,'../..');
const plan=fs.readdirSync(path.join(root,'plan')).map(n=>path.join(root,'plan',n)).find(p=>fs.existsSync(path.join(p,'preview/prefabs7')));
const dest=path.join(root,'plan/implementation/20261002212217');
const mode=process.argv[2]||'baseline',filter=process.argv[3];
const key=p=>p.join(','),point=n=>[n.x,n.y,n.z];
const S='gtsr:ruins_slag_masonry#0',V='gtsr:ruins_verdigris_pressed_brick#0',F='gtsr:ruins_sootstone_tiles#0';
const natural=m=>/ProsperityZenithLog|ProsperityJadeLeaves/.test(m||'');
const partial=m=>/stairs|railing|baluster|grate|pipe|valve|chair|bed_frame|pollution|tendril|slab|window|rubble|bracket|lamp|notice|seal_chest|index_frame|flow_window|phase_lens|workbench|cargo|drawer|ledger|oil_drum|coal_bin|filter_bed/.test(m||'');
const solid=m=>!!m&&!partial(m)&&!natural(m)&&!/(water|lava)#/.test(m);
function clearVoxelRay(cells,eye,target){const p=eye.map(Math.floor),end=target.map(Math.floor),dir=target.map((v,i)=>v-eye[i]),step=dir.map(v=>v>0?1:v<0?-1:0),delta=dir.map(v=>v?Math.abs(1/v):Infinity),next=dir.map((v,i)=>v?((step[i]>0?p[i]+1:p[i])-eye[i])/v:Infinity);for(let guard=0;guard<512;guard++){if(key(p)===key(end))return true;const mat=cells.get(key(p));if(mat&&!/(water|lava)#/.test(mat))return false;const t=Math.min(...next);if(t>1)return true;for(let i=0;i<3;i++)if(Math.abs(next[i]-t)<1e-10){p[i]+=step[i];next[i]+=delta[i];}}return false;}
function load(file,version){const w={window:{}};vm.createContext(w);vm.runInContext(fs.readFileSync(file,'utf8'),w);const values=w.window['REMASTER_PREFAB'+version+'_DATA'];return Object.values(values)[0];}
function decode(d){const m=new Map();for(const[x,y,z,n,i]of d.runs)for(let j=0;j<n;j++)m.set(key([x+j,y,z]),d.palette[i]);return m;}
function pack(map){const ps=[...map].map(([k,m])=>[...k.split(',').map(Number),m]);ps.sort((a,b)=>a[1]-b[1]||a[2]-b[2]||a[0]-b[0]);const palette=[],indices=new Map(),runs=[];for(const p of ps){if(!indices.has(p[3])){indices.set(p[3],palette.length);palette.push(p[3]);}const i=indices.get(p[3]),r=runs.at(-1);if(r&&r[1]===p[1]&&r[2]===p[2]&&r[0]+r[3]===p[0]&&r[4]===i)r[3]++;else runs.push([p[0],p[1],p[2],1,i]);}return{palette,runs,count:ps.length};}
function samples(points,width=5){const result=[];for(let j=1;j<(points||[]).length;j++){const a=points[j-1],b=points[j],dx=b[0]-a[0],dz=b[2]-a[2],steps=Math.max(Math.abs(dx),Math.abs(dz),Math.abs(b[1]-a[1]),1);for(let i=0;i<=steps;i++)result.push({p:a.map((n,k)=>Math.round(n+(b[k]-n)*i/steps)),alongX:Math.abs(dx)>=Math.abs(dz),half:Math.floor(width/2)});}return result;}
function makeProfile(m){const b=m.noticeBoard||{},rooms=m.rooms||[],mechs=m.shapeMechanisms||[];return{id:m.id,motif:m.typology,terrain:m.terrain,entry:{node:b.id,at:point(b),story:b.text},rooms:rooms.map(r=>({id:r.moduleId,purpose:r.function,task:r.task,intentionallyEmpty:!!r.corridor7?.empty||/empty/.test(r.flavor||''),at:[r.x,r.y,r.z],size:[r.w,r.h,r.d]})),mechanisms:mechs.map(s=>({id:s.id,kind:s.kind,control:s.control})),actors:[...new Set((m.spawns||[]).map(n=>n.code))],damage:(m.damageManifest||[]).map(d=>({cause:d.cause,puzzleLink:d.puzzleLink,removed:d.removedVoxels.length})),priorities:['入口局部视线/初见告示','转角与坡道净空','工序设备和现场许可','战利品接近风险与退出路线','敌人观察/掩体/退路'],terrainSurgery:m.terrain?.buried==='full'?'移除作者7入口与告示贯底填柱，保留两层梯廊基础':m.terrain?.buried==='half'?'将作者7下降填柱减为两层路基':'保留原建筑地基；仅审查交叉走廊',preserve:['节点身份','剧情原件门禁','Boss/原32王庭岗','天然木叶','作者事故断口','机关控制与delta','原房屋外墙/梁柱/屋盖']};}
function fitFactory(d){const m=d.metadata;if(m.id!=='subsided_factory'||m.factoryDepthFit)return;
 const knots=[[-176,-128],[-164,-116],[-139,-91],[-132,-90],[-116,-74],[-104,-68],[-88,-52],[-76,-46],[-60,-30],[-48,-24],[-32,-8],[0,0]];
 const mapY=y=>{if(y>=0)return y;if(y<=knots[0][0])return y+48;for(let i=1;i<knots.length;i++){const [a,b]=knots[i-1],[c,e]=knots[i];if(y<=c)return b+(y-a)*(e-b)/(c-a);}return y;};
 const coordinateKeys=new Set(['at','by','position','center','home','min','max','control','source','anchor','location','door','target','eye']);
 const listKeys=new Set(['points','routes','entrance','removedVoxels','surfaceAccess','explicitAir']);
 const yKeys=new Set(['y','ground','floorY','roofY','topY','bottomY','lowestRelativeY','surfaceY']);
 function visit(value,keyName=''){if(Array.isArray(value)){if(coordinateKeys.has(keyName)&&value.length===3&&value.every(n=>typeof n==='number'))return [value[0],Number.isInteger(value[1])?Math.round(mapY(value[1])):mapY(value[1]),value[2]];if(keyName==='bounds'&&value.length===6&&value.every(n=>typeof n==='number'))return value.map((n,i)=>i===1||i===4?Math.round(mapY(n)):n);if(listKeys.has(keyName))return value.map(v=>Array.isArray(v)&&v.length===3&&v.every(n=>typeof n==='number')?[v[0],Math.round(mapY(v[1])),v[2]]:visit(v,keyName==='routes'?'points':keyName));return value.map(v=>visit(v,keyName));}if(value&&typeof value==='object'){const out={};for(const[k,v]of Object.entries(value))out[k]=typeof v==='number'&&(yKeys.has(k)||k==='depth'&&v<0)?Math.round(mapY(v)):visit(v,k);return out;}return value;}
 const oldRooms=m.rooms.map(r=>({id:r.moduleId,y:r.y,h:r.h,roof:r.y+r.h+1})),oldCells=decode(d.voxel),mapped=new Map();
 for(const[k,mat]of oldCells){const p=k.split(',').map(Number);p[1]=Math.round(mapY(p[1]));mapped.set(key(p),mat);}
 d.metadata=visit(m);d.voxel=pack(mapped);
 const context=decode(d.context),mappedContext=new Map();for(const[k,mat]of context){const p=k.split(',').map(Number);p[1]=Math.round(mapY(p[1]));mappedContext.set(key(p),mat);}d.context=pack(mappedContext);
 const next=d.metadata;for(let i=0;i<oldRooms.length;i++){const r=oldRooms[i],nr=next.rooms[i];if(Math.round(mapY(r.roof))-nr.y!==r.h+1)throw Error('Factory room compressed '+r.id);}
 const minY=map=>[...map.keys()].reduce((n,k)=>Math.min(n,Number(k.split(',')[1])),Infinity),yMin=minY(mapped);next.burial.minCover=8;next.burial.topY=-8;next.burial.verticalPlacement.lowestRelativeY=yMin;next.burial.verticalPlacement.minSurfaceY=5-yMin;
 next.factoryDepthFit={knots,oldMinY:minY(oldCells),newMinY:yMin,roomHeightsUnchanged:true,bossRoomHeight:24,cover:8,policy:'仅压空层间与初段竖井，30房/五层工序/Boss室及演员高度保留；需真实维度高地与基岩裕量'};
}
function refine(d,old,apply,profile){const m=d.metadata,cells=decode(d.voxel),original=new Map(cells),get=p=>cells.get(key(p));
 const removed=new Map(),added=new Map(),shortfalls=[],repairs=[];
 const damage=new Set((m.damageManifest||[]).flatMap(x=>(x.removedVoxels||[]).map(p=>key(p.slice(0,3)))));
 const mechanisms=new Set((m.shapeMechanisms||[]).flatMap(s=>[s.control,...(s.delta||[]).map(x=>x.at)]).filter(Boolean).map(key));
 const objectCells=new Set((m.nodes||[]).map(n=>key(point(n))));
 const rooms=m.rooms||[],bounds=(r,p,pad=0)=>p[0]>=r.x-pad&&p[0]<=r.x+r.w-1+pad&&p[2]>=r.z-pad&&p[2]<=r.z+r.d-1+pad&&p[1]>=r.y-1&&p[1]<=r.y+r.h+Math.max(9,r.roofHeight||9);
 const shell=p=>rooms.some(r=>bounds(r,p)&&((p[0]===r.x||p[0]===r.x+r.w-1||p[2]===r.z||p[2]===r.z+r.d-1)||p[1]<=r.y+1||p[1]>=r.y+r.h-1));
 const boss=p=>(m.bossProtectedVolumes||[]).some(b=>p.every((n,i)=>n>=b.min[i]&&n<=b.max[i]));
 const actors=p=>(m.spawns||[]).some(n=>{const c=n.clearance||{width:3,depth:3,height:3};return Math.abs(p[0]-n.x)<c.width/2+.5&&Math.abs(p[2]-n.z)<c.depth/2+.5&&p[1]>=n.y-1&&p[1]<n.y+c.height;})||(m.spawnerPlan||[]).some(n=>{const q=n.spawnZone?.center||point(n),c=n.spawnZone?.clearance||{width:3,depth:3,height:3};return Math.abs(p[0]-q[0])<c.width/2+.5&&Math.abs(p[2]-q[2])<c.depth/2+.5&&p[1]>=q[1]-1&&p[1]<q[1]+c.height;});
 const protectedAt=p=>damage.has(key(p))||mechanisms.has(key(p))||objectCells.has(key(p))||natural(get(p))||actors(p);
 function remove(p,why){const k=key(p),mat=get(p);if(!mat||protectedAt(p))return false;if(!removed.has(k))removed.set(k,{at:p,material:mat,why});if(apply)cells.delete(k);return true;}
 function add(p,mat,why){if(get(p)||protectedAt(p)||boss(p))return false;const k=key(p);if(!added.has(k))added.set(k,{at:p,material:mat,why});if(apply)cells.set(k,mat);return true;}
 const routes=(m.stairRoutes||[]).map(r=>({points:r.points,width:r.width||5,source:r.task||'authored-stair'}));
 if(!routes.length)for(const points of m.routes||[])routes.push({points,width:5,source:'authored-route'});
 const steps=routes.flatMap(r=>samples(r.points,r.width).map(q=>({...q,source:r.source})));
 // Exact envelopes generated by author7.connect and older corridor builders. Never material-filter the whole building.
 const envelope=new Set(),lane=new Set();
 for(const q of steps){const [x,y,z]=q.p,w=q.half+1;for(let s=-w;s<=w;s++){const xx=x+(q.alongX?0:s),zz=z+(q.alongX?s:0);envelope.add(key([xx,y+7,zz]));if(Math.abs(s)===w)for(let h=1;h<=6;h++)envelope.add(key([xx,y+h,zz]));}for(let s=-Math.min(2,q.half);s<=Math.min(2,q.half);s++)for(let h=1;h<=4;h++)lane.add(key([x+(q.alongX?0:s),y+h,z+(q.alongX?s:0)]));}
 const routeBefore=[];for(const q of steps)for(let h=1;h<=2;h++){const p=[q.p[0],q.p[1]+h,q.p[2]],mat=get(p);if(mat&&!partial(mat)&&!natural(mat))routeBefore.push({at:p,material:mat,route:q.source});}
 for(const k of lane){const p=k.split(',').map(Number),mat=get(p);if(!mat||shell(p)||protectedAt(p))continue;if(envelope.has(k)&&(mat===V||mat===S))remove(p,'交叉走廊侧墙/低顶进入另一条已编制通路');}
 // The old stair builder used a width×width deck at EVERY rising step. Its front/rear overlap buries adjacent lower steps.
 // Recover the author's one-step transverse section, and remove only upper tiles with that exact generated provenance.
 const stairDeck=new Set(),stairSpine=new Map(),directFloors=new Set(steps.flatMap(q=>{const out=[];for(let s=-q.half;s<=q.half;s++)out.push(key([q.p[0]+(q.alongX?0:s),q.p[1],q.p[2]+(q.alongX?s:0)]));return out;}));
 for(const r of routes)for(let j=1;j<r.points.length;j++){const a=r.points[j-1],b=r.points[j];if(a[1]===b[1])continue;for(const q of samples([a,b],r.width)){for(let dx=-q.half;dx<=q.half;dx++)for(let dz=-q.half;dz<=q.half;dz++)stairDeck.add(key([q.p[0]+dx,q.p[1],q.p[2]+dz]));for(let s=-q.half;s<=q.half;s++){const x=q.p[0]+(q.alongX?0:s),z=q.p[2]+(q.alongX?s:0),k=[x,z].join(',');if(!stairSpine.has(k))stairSpine.set(k,q.p[1]);else stairSpine.set(k,Math.min(stairSpine.get(k),q.p[1]));}}}
 for(const[xz,y]of stairSpine){const[x,z]=xz.split(',').map(Number);for(let h=1;h<=4;h++){const p=[x,y+h,z];if([F,S].includes(get(p))&&stairDeck.has(key(p))&&!directFloors.has(key(p))&&!protectedAt(p))remove(p,'斜梯逐步5×5地坪/岩基前后覆叠；保留各步横截面而清上层误盖');}}
 // An ascending flight may start underneath a duplicate approach floor. Only its first two steps are eligible.
 for(const r of routes){const ss=samples(r.points,r.width);for(const q of ss.slice(0,2)){for(let h=1;h<=2;h++){const p=[q.p[0],q.p[1]+h,q.p[2]],mat=get(p);if(mat===F&&!shell(p)&&!protectedAt(p))remove(p,'原路线起步与重复高差地坪叠置');}}}
 // The giant entrance column is authored7-only, outside structural rooms and actor/mechanism volumes.
 const terrain=m.terrain||{},entrance=terrain.entrance||[],entrySamples=Array.isArray(entrance)&&entrance.length>1?samples(entrance,terrain.buried==='half'?5:7):[];
 let towerBefore=0;if(['full','half'].includes(terrain.buried)&&m.id!=='subsided_factory'&&old){const oldCells=decode(old.voxel),columnTops=new Map();for(const q of entrySamples){const range=terrain.buried==='half'?4:5;for(let dx=-range;dx<=range;dx++)for(let dz=-range;dz<=range;dz++){if(terrain.buried==='half'&&dz!==0)continue;const k=[q.p[0]+dx,q.p[2]+dz].join(',');columnTops.set(k,Math.max(columnTops.get(k)??-Infinity,q.p[1]));}}
  const board=m.noticeBoard;if(board)for(let dx=-2;dx<=2;dx++)for(let dz=-2;dz<=2;dz++)columnTops.set([board.x+dx,board.z+dz].join(','),0);
  for(const [k,mat]of original){if(mat!==S||oldCells.has(k))continue;const p=k.split(',').map(Number),top=columnTops.get([p[0],p[2]].join(','));if(top===undefined||p[1]>=top-1||directFloors.has(k)||directFloors.has(key([p[0],p[1]+1,p[2]]))||rooms.some(r=>bounds(r,p,1))||protectedAt(p))continue;towerBefore++;remove(p,'入口/告示贯底背景岩柱移除；梯廊仅保留连续两层路基');}
 }
 function stand(p){const foot=get([p[0],p[1]-1,p[2]]);return(solid(foot)||natural(foot))&&!get(p)&&!get([p[0],p[1]+1,p[2]])&&!actors(p);}
 function approaches(n,max=1){const p=point(n),result=[];for(let r=1;r<=max;r++)for(const [dx,dz]of [[r,0],[-r,0],[0,r],[0,-r]])for(const dy of [0,-1,1]){const q=[p[0]+dx,p[1]+dy,p[2]+dz];if(stand(q))result.push(q);}return result;}
 // Relocate accidental movable furniture on a documented main lane, never discard its room purpose.
 if(apply)for(const k of lane){const p=k.split(',').map(Number),mat=get(p);if(!/^gtsr:draft6_(chair|workbench)#/.test(mat||'')||protectedAt(p)||get([p[0],p[1]+1,p[2]]))continue;const r=rooms.find(r=>bounds(r,p)&&p[0]>r.x&&p[0]<r.x+r.w-1&&p[2]>r.z&&p[2]<r.z+r.d-1);if(!r)continue;let candidate=null;outer:for(let z=r.z+3;z<r.z+r.d-3;z+=3)for(const x of [r.x+2,r.x+r.w-3]){const q=[x,p[1],z];if(!get(q)&&!get([x,p[1]+1,z])&&solid(get([x,p[1]-1,z]))&&!lane.has(key(q))&&!protectedAt(q)){candidate=q;break outer;}}if(candidate){cells.delete(k);cells.set(key(candidate),mat);removed.set(k,{at:p,material:mat,why:'主路误放可搬家具迁回工序侧袋'});added.set(key(candidate),{at:candidate,material:mat,why:'保留原家具与房间职责'});for(const fixture of r.interior?.revision6Fixtures||[])if(key(fixture.at||[])===k)fixture.at=candidate;repairs.push({room:r.moduleId,from:p,to:candidate,kind:'movable-furniture-relocation'});}}
 const interactables=(m.nodes||[]).filter(n=>['control','memory','chest','testimony','puzzle-object'].includes(n.role));
 const inaccessibleBefore=interactables.filter(n=>!approaches(n).length).map(n=>({id:n.id,role:n.role,at:point(n)}));
 // Provide an approach on an existing room floor, without erasing the target or its puzzle cells.
 for(const n of interactables){if(approaches(n).length)continue;const p=point(n);let fixed=false;
  outer:for(let r=1;r<=2;r++)for(const [dx,dz]of [[r,0],[-r,0],[0,r],[0,-r]])for(const dy of [0,-1,1]){const q=[p[0]+dx,p[1]+dy,p[2]+dz],base=[q[0],q[1]-1,q[2]];if([q,[q[0],q[1]+1,q[2]],base].some(protectedAt))continue;const foot=get(base);if(!solid(foot))continue;const obstacles=[q,[q[0],q[1]+1,q[2]]].filter(v=>get(v));if(obstacles.some(v=>shell(v)||!envelope.has(key(v))||![S,V,F].includes(get(v))))continue;for(const v of obstacles)remove(v,'现场操作面被作者走廊围护遮挡');if(!obstacles.length||apply&&stand(q)){fixed=true;repairs.push({node:n.id,approach:q,kind:'existing-floor-approach'});break outer;}}
  if(!fixed&&['memory','puzzle-object','chest'].includes(n.role)){
   // Move only the movable object, preserving stable node ID and every gate reference.
   let candidate=null;outer:for(let r=1;r<=5;r++)for(let dx=-r;dx<=r;dx++)for(let dz=-r;dz<=r;dz++){if(Math.max(Math.abs(dx),Math.abs(dz))!==r)continue;const q=[p[0]+dx,p[1],p[2]+dz];if(get(q)||!solid(get([q[0],q[1]-1,q[2]]))||protectedAt(q)||shell(q)||!approaches({x:q[0],y:q[1],z:q[2]}).length)continue;candidate=q;break outer;}
   if(candidate){const mat=get(p);if(mat&&!mechanisms.has(key(p))&&!natural(mat)){if(apply){cells.delete(key(p));cells.set(key(candidate),mat);removed.set(key(p),{at:p,material:mat,why:'可交互对象移至有实体相邻操作面的可见侧袋'});added.set(key(candidate),{at:candidate,material:mat,why:'保留节点身份与门禁关联'});for(const a of [m.nodes,m.puzzleObjects7,m.lootPlan7])for(const ref of a||[])if(ref.id===n.id){ref.x=candidate[0];ref.y=candidate[1];ref.z=candidate[2];}if(m.noticeBoard?.id===n.id){m.noticeBoard.x=candidate[0];m.noticeBoard.y=candidate[1];m.noticeBoard.z=candidate[2];}objectCells.delete(key(p));objectCells.add(key(candidate));}repairs.push({node:n.id,from:p,to:candidate,kind:'relocated-visible-operating-object',preservedReference:n.reference||n.target||null});fixed=true;}}
  }
  if(!fixed)shortfalls.push({kind:'interaction-approach',node:n.id,role:n.role,at:p,reason:'没有不破坏承重/家具/机关的相邻实体操作面；保留节点等待专属结构设计'});
 }
 // Small, purpose-specific author groups: no infill in evacuated rooms or boss arenas.
 const detailGroups=[];
 if(apply&&!m.structureDesignReview)for(const r of rooms){if(r.corridor7?.empty||/empty/.test(r.flavor||'')||boss([r.x+r.w/2,r.y+2,r.z+r.d/2]))continue;
  const purpose=r.function||profile.motif||'',suite=/档案|索引|名籍|观测|校核|信号/.test(purpose)?['archive_drawer','dispatch_ledger','parts_drawer']:/救援|床|生活|宿|物资/.test(purpose)?['cargo_crate','canteen_table','dispatch_ledger']:/水|冷却|筛洗|回流|沉渣/.test(purpose)?['filter_bed','oil_drum','dispatch_ledger']:/铸|炉|锅|砂|热/.test(purpose)?['coal_bin','brick_pallet','dispatch_ledger']:['parts_drawer','cargo_crate','dispatch_ledger'];
  let count=0;const placed=[];for(const [x,z]of [[r.x+2,r.z+4],[r.x+r.w-3,r.z+r.d-5],[r.x+2,r.z+r.d-5],[r.x+r.w-3,r.z+4]]){if(count>=2)break;const p=[x,r.y+2,z];if(!solid(get([x,r.y+1,z]))||get(p)||get([x,r.y+3,z])||protectedAt(p)||lane.has(key(p)))continue;const materials=[suite[count%suite.length],suite[2]],side=x===r.x+2?1:-1;let actual=0;for(let j=0;j<2;j++){const q=[x+j*side,r.y+2,z];if(lane.has(key(q))||!solid(get([q[0],q[1]-1,q[2]]))||!approaches({x:q[0],y:q[1],z:q[2]},2).length)continue;if(add(q,'gtsr:draft_'+materials[j]+'#0','房间工序侧袋细节：'+purpose)){placed.push({at:q,material:'gtsr:draft_'+materials[j]+'#0'});actual++;}}if(actual)count++;}
  if(placed.length)detailGroups.push({room:r.moduleId,purpose,task:r.task,placed});
 }
 // Human eye viewpoints, grounded in walkable local samples; used by the root browser review.
 const cameras=[],turns=[];for(const r of routes)for(let i=1;i<r.points.length-1;i++)turns.push(r.points[i]);
 const targets=[{kind:'entrance',node:m.noticeBoard},...turns.slice(0,3).map(p=>({kind:'turn',node:{x:p[0],y:p[1]+1,z:p[2],id:'route-turn'}})),...(m.shapeMechanisms||[]).slice(0,3).map(s=>({kind:'mechanism',node:{x:s.control[0],y:s.control[1],z:s.control[2],id:s.id}})),...(m.lootPlan7||[]).slice(0,2).map(n=>({kind:'loot',node:n})),...(m.spawns||[]).slice(0,2).map(n=>({kind:'enemy',node:n}))];
 for(const t of targets){if(!t.node)continue;const n=t.node,target=point(n);let position=null;for(const r of [3,5,8,12]){for(const [dx,dz]of [[0,-r],[-r,0],[r,0],[0,r],[-r,-r],[r,-r]])for(const dy of [0,-1,1,-2,2]){const p=[target[0]+dx,target[1]+dy,target[2]+dz];if(stand(p)){position=p;break;}}if(position)break;}if(!position&&t.kind==='entrance'){let best=Infinity;for(const[k,mat]of cells){if(!solid(mat)&&!natural(mat))continue;const base=k.split(',').map(Number),p=[base[0],base[1]+1,base[2]],distance=Math.hypot(p[0]-target[0],p[1]-target[1],p[2]-target[2]);if(distance<best&&stand(p)){best=distance;position=p;}}}if(!position){shortfalls.push({kind:'eye-view',target:n.id,category:t.kind,reason:'目标附近没有可证实的眼高站位'});continue;}
  const eye=[position[0]+.5,position[1]+1.62,position[2]+.5],aim=[target[0]+.5,target[1]+.7,target[2]+.5],occluded=[];for(let j=1;j<24;j++){const p=eye.map((v,k)=>Math.floor(v+(aim[k]-v)*j/24)),mat=get(p);if(solid(mat)&&key(p)!==key(target)&&!occluded.some(v=>key(v.at)===key(p)))occluded.push({at:p,material:mat});}
  cameras.push({category:t.kind,targetId:n.id,eye,target:aim,floor:{at:[position[0],position[1]-1,position[2]],material:get([position[0],position[1]-1,position[2]])},headClearance:{feet:position,head:[position[0],position[1]+1,position[2]],clear:true},lineOfSight:occluded.length?'occluded':'clear',occluders:occluded.slice(0,8),notes:t.kind==='enemy'?'核掩体、观察距、退路与预警；遮挡可为刻意战术边界':t.kind==='loot'?'核奖励风险、箱型与解锁指引；不得穿墙定位':'核局部留白、用途痕迹、提示可读和折入路径'});
 }
 const routeAfter=[];for(const q of steps)for(let h=1;h<=2;h++){const p=[q.p[0],q.p[1]+h,q.p[2]],mat=get(p);if(mat&&!partial(mat)&&!natural(mat))routeAfter.push({at:p,material:mat,route:q.source});}
 const inaccessibleAfter=interactables.filter(n=>!approaches(n).length).map(n=>({id:n.id,role:n.role,at:point(n)}));
 const actorViolations=[];for(const n of m.spawns||[]){const c=n.clearance;if(!c)continue;const rx=(c.width-1)/2,rz=(c.depth-1)/2;for(let x=n.x-rx;x<=n.x+rx;x++)for(let z=n.z-rz;z<=n.z+rz;z++){if(c.mode!=='aerial'&&!get([x,n.y-1,z]))actorViolations.push({id:n.id,type:'unsupported'});for(let y=n.y;y<n.y+c.height;y++)if(get([x,y,z]))actorViolations.push({id:n.id,type:'occupied',at:[x,y,z]});}}
 const preserved={natural:0,mechanism:0,damage:0};for(const[k,mat]of original)if(natural(mat)&&cells.get(k)!==mat)preserved.natural++;for(const k of mechanisms)if(original.get(k)!==cells.get(k))preserved.mechanism++;for(const k of damage)if(cells.has(k))preserved.damage++;
 if(apply){const labels={entrance:'入口现场',turn:'转角与回返',mechanism:'机关操作面',loot:'战利品接近',enemy:'敌人观察与退路'},seen=new Map();m.playerReviewViews=cameras.map(c=>{const id=c.category==='mechanism'?'control':c.category,n=seen.get(id)||0;seen.set(id,n+1);return{id:id+(n?'-'+n:''),label:labels[c.category],eye:c.eye,target:c.target,floor:c.floor,headClearance:c.headClearance,lineOfSight:c.lineOfSight,targetId:c.targetId};});m.playerReviewAbsentViews=['entrance','turn','mechanism','loot','enemy'].filter(k=>!cameras.some(c=>c.category===k)).map(k=>({id:k==='mechanism'?'control':k,absentReason:targets.some(t=>t.kind===k)?'对应对象存在，但附近没有不穿实体/危险区的有效眼高站位':'该方案没有对应对象或转角，不新增虚构对象'}));m.structureDesignReview={revision:8,profile:m.id,removed:removed.size,added:added.size,interactionRepairs:repairs,detailGroups,cameras,explicitAir:[...removed.values()].map(r=>r.at),limits:'离线整数体素/眼高候选，非实机碰撞/光照/玩家审美通过'};d.voxel=pack(cells);}
 return{id:m.id,variant:m.variant,motif:profile.motif,roomPurposes:m.rooms.map(r=>({id:r.moduleId,purpose:r.function,task:r.task,at:[r.x,r.y,r.z],size:[r.w,r.h,r.d]})),terrainDecision:profile.terrainSurgery,factoryDepthFit:m.factoryDepthFit||null,before:{voxels:original.size,routeSolidSamples:routeBefore.length,nodesWithoutApproach:inaccessibleBefore.length,deepEntranceFill:towerBefore},after:{voxels:cells.size,routeSolidSamples:routeAfter.length,nodesWithoutApproach:inaccessibleAfter.length,actorViolations:actorViolations.length},removed:[...removed.values()],added:[...added.values()],interactionRepairs:repairs,detailGroups,cameras,remainingRouteSamples:routeAfter.slice(0,36),remainingNodeApproaches:inaccessibleAfter,shortfalls,preserved,damageReasons:profile.damage,reviewStatus:actorViolations.length||Object.values(preserved).some(Boolean)?'failed-preservation':'offline-reviewed-runtime-and-player-view-pending'};
}
if(mode==='local-guidance'){
 const records=[],errors=[],reviewFile=path.join(dest,'structure-review.json'),review=JSON.parse(fs.readFileSync(reviewFile,'utf8'));
 const names={north:'北',south:'南',east:'东',west:'西'};
 for(const file of fs.readdirSync(path.join(plan,'preview/prefabs7')).filter(n=>n.endsWith('.js')).sort()){
  const d=load(path.join(plan,'preview/prefabs7',file),7),m=d.metadata,cells=decode(d.voxel),get=p=>cells.get(key(p));
  const actorAt=p=>[...(m.spawns||[]),...(m.spawnerPlan||[]).map(n=>({...n,...Object.fromEntries(['x','y','z'].map((k,i)=>[k,n.spawnZone?.center[i]??n[k]])),clearance:n.spawnZone?.clearance}))].some(n=>{const c=n.clearance||{width:3,depth:3,height:3};return Math.abs(p[0]-n.x)<c.width/2+1&&Math.abs(p[2]-n.z)<c.depth/2+1&&p[1]+2>n.y&&p[1]<n.y+c.height;});
  const stand=p=>solid(get([p[0],p[1]-1,p[2]]))&&!get(p)&&!get([p[0],p[1]+1,p[2]])&&!actorAt(p);
  function ray(eye,target){return Math.hypot(...eye.map((v,i)=>v-target[i]))<=8&&clearVoxelRay(cells,eye,target);}
  function proof(n,preferred){const target=point(n).map(v=>v+.5);const candidates=[];if(preferred?.headClearance?.feet)candidates.push(preferred.headClearance.feet);for(let r=1;r<=7;r++)for(const[dx,dz]of [[r,0],[-r,0],[0,r],[0,-r],[r,r],[-r,-r],[r,-r],[-r,r]])for(const dy of [0,1,-1,2,-2])candidates.push([n.x+dx,n.y+dy,n.z+dz]);for(const feet of candidates){if(!stand(feet))continue;const eye=[feet[0]+.5,feet[1]+1.62,feet[2]+.5];if(ray(eye,target))return{node:n.id,role:'memory',navigationHint:true,target,targetBlock:n.block,feet,eye,floor:{at:[feet[0],feet[1]-1,feet[2]],material:get([feet[0],feet[1]-1,feet[2]])},distance:Math.round(Math.hypot(...eye.map((v,i)=>v-target[i]))*1000)/1000,headClearance:true,rayUnobstructed:true};}return null;}
  const preserved=new Set([...m.nodes.map(n=>key(point(n))),...(m.shapeMechanisms||[]).flatMap(s=>[s.control,...s.delta.map(v=>v.at)]).map(key),...(m.damageManifest||[]).flatMap(d=>d.removedVoxels.map(p=>key(p.slice(0,3)))),...(m.playerReviewViews||[]).flatMap(v=>[v.headClearance.feet,v.headClearance.head]).map(key)]);
  const boss=p=>(m.bossProtectedVolumes||[]).some(b=>p.every((n,i)=>n>=b.min[i]&&n<=b.max[i]));
  const emptyRoom=p=>m.rooms.some(r=>(r.corridor7?.empty||/empty/.test(r.flavor||''))&&p[0]>=r.x&&p[0]<r.x+r.w&&p[2]>=r.z&&p[2]<r.z+r.d&&p[1]>=r.y&&p[1]<=r.y+r.h);
  const hints=m.navigationHints||[],sources=[],skips=[];
  const joints=[];for(const r of m.stairRoutes||[])for(let j=1;j<r.points.length-1;j++)joints.push({p:r.points[j],next:r.points[j+1],source:'authored-turn'});
  const viewTurns=(m.playerReviewViews||[]).filter(v=>v.id==='turn'||v.id.startsWith('turn-'));
  for(const v of viewTurns){const p=v.headClearance.feet;const joint=joints.slice().sort((a,b)=>Math.hypot(...a.p.map((n,i)=>n-p[i]))-Math.hypot(...b.p.map((n,i)=>n-p[i])))[0];const next=joint?.next||m.rooms.slice().sort((a,b)=>Math.hypot(a.x+a.w/2-p[0],a.z+a.d/2-p[2])-Math.hypot(b.x+b.w/2-p[0],b.z+b.d/2-p[2]))[0];const target=Array.isArray(next)?next:next?[next.x+Math.floor(next.w/2),next.y+1,next.z]:null;if(target)sources.push({kind:'turn',anchor:p,target,view:v});}
  if(m.id==='subsided_factory')for(const l of m.factoryLevels.slice(0,4)){const r=m.rooms.find(r=>r.function===l.name),route=(m.factoryCorridor7?.branches||[]).find(b=>b.level===l.index);if(r&&route)sources.push({kind:'factory-junction',anchor:[r.x+Math.floor(r.w/2),r.y+2,r.z+8],target:route.points[0],purpose:l.name,level:l.index+1});}
  if(!sources.length){const entry=m.playerReviewViews.find(v=>v.id==='entrance'),target=m.nodes.find(n=>n.role==='control')||m.nodes.find(n=>n.role==='puzzle-object');if(entry&&target)sources.push({kind:'entry-direction',anchor:entry.headClearance.feet,target:point(target),view:entry,purpose:target.label});}
  if(m.id==='fallen_foundry')for(const v of m.playerReviewViews.filter(v=>v.id==='loot'||v.id.startsWith('loot-')).slice(0,2)){const chest=m.lootPlan7.find(n=>n.id===v.targetId);if(chest)sources.push({kind:'sealed-loot',anchor:point(chest),target:point(chest),view:v,chest});}
  const max=m.id==='subsided_factory'?7:m.id==='fallen_foundry'?5:3;
  for(const source of sources){if(hints.length>=max)break;if(hints.some(n=>n.sourceKind===source.kind&&key(n.guideTarget)===key(source.target.map(Math.round))||Math.hypot(n.x-source.anchor[0],n.y-source.anchor[1],n.z-source.anchor[2])<8))continue;
   const p=source.anchor,target=source.target,dx=target[0]-p[0],dz=target[2]-p[2],dy=target[1]-p[1];const dir=names[Math.abs(dx)>Math.abs(dz)?dx>=0?'east':'west':dz>=0?'south':'north'];
   const room=m.rooms.slice().sort((a,b)=>Math.hypot(a.x+a.w/2-target[0],a.z+a.d/2-target[2])+Math.abs(a.y+1-target[1])*5-Math.hypot(b.x+b.w/2-target[0],b.z+b.d/2-target[2])-Math.abs(b.y+1-target[1])*5)[0];
   const purpose=source.purpose||room?.function||'下一段检修通道',level=m.factoryLevels?.slice().sort((a,b)=>Math.abs(a.floorY-target[1])-Math.abs(b.floorY-target[1]))[0];
   let text=source.chest?('封印箱｜'+(source.chest.kind==='exploration'?'维护补给：右键领取一次，不含身份原件。':source.chest.kind==='combat'?'本处驻守解除后解封；先观察守位，留出返回侧道。':source.chest.kind==='boss'?'本厅首领解除后解封；中央留作避让，奖励领取一次。':'本房工序恢复后解封；先查阅工单，再到操作面核验。')):('检修路标｜向'+dir+(Math.abs(dy)>3?dy<0?'沿楼梯下行':'沿楼梯上行':'沿本层通道')+'，前往'+(level?'第'+(level.index+1)+'工作层 · ':'')+purpose+'。绕柱走已铺通道；原路可返回，勿从事故缺口跳层。');
   const candidates=[];for(let radius=2;radius<=(source.kind==='sealed-loot'?12:7);radius++)for(const[ox,oz]of [[radius,0],[-radius,0],[0,radius],[0,-radius],[radius,radius],[-radius,-radius]])for(const oy of [0,1,-1]){const q=[p[0]+ox,p[1]+oy,p[2]+oz];if(preserved.has(key(q))||get(q)||!solid(get([q[0],q[1]-1,q[2]]))||actorAt(q)||boss(q)||emptyRoom(q))continue;const wall=[[1,0],[-1,0],[0,1],[0,-1]].some(([x,z])=>solid(get([q[0]+x,q[1],q[2]+z])));candidates.push({q,score:(wall?0:15)+radius+Math.abs(oy)*3});}
   candidates.sort((a,b)=>a.score-b.score);let placed=null;
   for(const {q}of candidates){const id='p8-route-hint-'+q.join('-'),n={id,role:'memory',navigationHint:true,block:'gtsr:draft_notice_board#0',x:q[0],y:q[1],z:q[2],text,guideTarget:target.map(Math.round),guidePurpose:purpose,sourceKind:source.kind,readOnly:true};cells.set(key(q),n.block);const evidence=proof(n,source.view);if(evidence){placed={n,evidence};break;}cells.delete(key(q));}
   if(!placed){skips.push({kind:source.kind,anchor:source.anchor,target:source.target,reason:'没有既有承重侧带且不占演员/剧情空室/机关/事故缺口的可读实体牌位；不造台座'});continue;}
   hints.push(placed.n);preserved.add(key(point(placed.n)));m.interactionApproaches.push(placed.evidence);m.playerReviewViews.push({id:'route-hint-'+hints.length,label:source.kind==='sealed-loot'?'封印箱风险与解封提示':'近处转角与工序路标',eye:placed.evidence.eye,target:placed.evidence.target,floor:placed.evidence.floor,headClearance:{feet:placed.evidence.feet,head:[placed.evidence.feet[0],placed.evidence.feet[1]+1,placed.evidence.feet[2]],clear:true},lineOfSight:'clear',targetId:placed.n.id});
  }
  m.navigationHints=hints;m.navigationHintCoverage={required:hints.length,verified:hints.filter(n=>proof(n)).length,missing:hints.filter(n=>!proof(n)).length,skips};m.interactionApproachCoverage.required=m.nodes.filter(n=>['control','memory','chest','testimony','puzzle-object'].includes(n.role)).length+hints.length;m.interactionApproachCoverage.verified=m.interactionApproaches.length;m.interactionApproachCoverage.missing=m.interactionApproachCoverage.required-m.interactionApproachCoverage.verified;
  if(m.id==='subsided_factory'){m.terrain.cover=8;m.terrain.highestBuildingY=Math.max(...m.rooms.map(r=>r.y+r.h+1));m.factoryDepthFit.cover=8;m.burial.minCover=8;}
  if(m.navigationHintCoverage.missing||m.interactionApproachCoverage.missing)errors.push(file+': navigation interaction mismatch');
  d.voxel=pack(cells);const k=m.id+'-v'+m.variant;fs.writeFileSync(path.join(plan,'preview/prefabs7',file),'window.REMASTER_PREFAB7_DATA=window.REMASTER_PREFAB7_DATA||{};window.REMASTER_PREFAB7_DATA['+JSON.stringify(k)+']='+JSON.stringify(d)+';');
  const record={id:m.id,variant:m.variant,navigationHints:hints,coverage:m.navigationHintCoverage,interactionCoverage:m.interactionApproachCoverage,factoryTerrain:m.id==='subsided_factory'?m.terrain:null};records.push(record);const row=review.rows.find(r=>r.id===m.id&&r.variant===m.variant);if(row){row.navigationHints=hints;row.navigationHintCoverage=m.navigationHintCoverage;row.interactionApproaches=m.interactionApproaches;row.interactionApproachCoverage=m.interactionApproachCoverage;row.playerReviewViews=m.playerReviewViews;row.after.voxels=d.voxel.count;}
 }
 const report={pass:!errors.length,structures:new Set(records.map(r=>r.id)).size,variants:records.length,hints:records.reduce((n,r)=>n+r.navigationHints.length,0),missing:records.reduce((n,r)=>n+r.coverage.missing,0),errors,records,limits:'现场新告示已编成实际体素；静态眼高ray可读，不等于Minecraft实机引导体验通过'};review.summary.navigationHints=report.hints;review.summary.navigationHintMissing=report.missing;review.summary.visibleInteractionVerified=records.reduce((n,r)=>n+r.interactionCoverage.verified,0);review.summary.visibleInteractionMissing=records.reduce((n,r)=>n+r.interactionCoverage.missing,0);fs.writeFileSync(reviewFile,JSON.stringify(review,null,2)+'\n');fs.appendFileSync(path.join(dest,'structure-review.md'),'\n## 局部转角与箱旁引导增量\n\n新增'+report.hints+'个只读现场方向/楼层/用途/封印条件牌位，真实体素与人物近视点同源；新增操作位缺口'+report.missing+'。不以读取写剧情进度，不提供参数答案，不拆承重柱墙或增台座。\n');fs.writeFileSync(path.join(root,'temp/structure-design-local-guidance.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({pass:report.pass,structures:report.structures,variants:report.variants,hints:report.hints,missing:report.missing,errors:report.errors}));process.exit(report.pass?0:1);
}
if(mode==='surface-testimony'){
 const prior=JSON.parse(fs.readFileSync(path.join(plan,'config/revision7-structure-plan.json'),'utf8')),records=[],reviewFile=path.join(dest,'structure-review.json'),review=JSON.parse(fs.readFileSync(reviewFile,'utf8'));
 for(let variant=0;variant<3;variant++){
  const file=path.join(plan,'preview/prefabs7/fiction_expansion_project-v'+variant+'.js'),d=load(file,7),m=d.metadata,cells=decode(d.voxel),old=prior.find(a=>a.id===m.id&&a.variant===variant),moves=[];
  for(const n of m.nodes.filter(n=>n.role==='testimony')){const original=old.nodes.find(a=>a.id===n.id);if(Math.abs(n.y-original.y)<=8)continue;const from=point(n),to=point(original),material=cells.get(key(from));if(material!=='gtsr:draft5_hush_inscription#0'||cells.has(key(to))||cells.get(key([to[0],3,to[2]]))!==material)throw new Error('surface pedestal identity mismatch '+n.id);cells.set(key(to),material);
   let proof=null;outer:for(let r=1;r<=7;r++)for(let dx=-r;dx<=r;dx++)for(let dz=-r;dz<=r;dz++){if(Math.max(Math.abs(dx),Math.abs(dz))!==r)continue;for(const dy of [0,-1,1,-2,2,-3,3]){const feet=[to[0]+dx,to[1]+dy,to[2]+dz],floorAt=[feet[0],feet[1]-1,feet[2]],floor=cells.get(key(floorAt));if(!solid(floor)||cells.has(key(feet))||cells.has(key([feet[0],feet[1]+1,feet[2]])))continue;const eye=[feet[0]+.5,feet[1]+1.62,feet[2]+.5],target=to.map(v=>v+.5),distance=Math.hypot(...eye.map((v,i)=>v-target[i]));if(distance<=8&&clearVoxelRay(cells,eye,target)){proof={node:n.id,role:n.role,target,targetBlock:material,feet,eye,floor:{at:floorAt,material:floor},distance,headClearance:true,rayUnobstructed:true};break outer;}}}
   if(!proof)throw new Error('no surface operating stand '+n.id);cells.delete(key(from));
   function sync(value){if(Array.isArray(value)){value.forEach(sync);return;}if(!value||typeof value!=='object')return;if(value.id===n.id&&'x'in value){[value.x,value.y,value.z]=to;}Object.values(value).forEach(sync);}sync(m);
   m.interactionApproaches=m.interactionApproaches.map(a=>a.node===n.id?proof:a);for(const v of m.playerReviewViews||[])if(v.targetId===n.id){v.eye=proof.eye;v.target=proof.target;v.floor=proof.floor;v.headClearance={feet:proof.feet,head:[proof.feet[0],proof.feet[1]+1,proof.feet[2]],clear:true};v.lineOfSight='clear';}
   m.structureDesignReview.explicitAir=[...m.structureDesignReview.explicitAir.filter(p=>key(p)!==key(to)),from];moves.push({id:n.id,code:n.code,from,to,proof,originalDuty:'地面半径43的38座身份信物环形台座；保原碑及台基，撤掉误放地下的副碑',source:'plan/临时计划/preview/author5.js:216-218',collisionEvidence:proof.floor.material==='gtsr:draft5_pressure_band#0'?'RemasterBlocks.block50: cube AABB [0,0,0,1,1,1]':'既有整块工业地坪'});
  }
  if(moves.length!==6)throw new Error('expected six historical cross-layer errors, got '+moves.length);m.structureDesignReview.surfaceTestimonyRestoration=moves;d.voxel=pack(cells);fs.writeFileSync(file,'window.REMASTER_PREFAB7_DATA=window.REMASTER_PREFAB7_DATA||{};window.REMASTER_PREFAB7_DATA['+JSON.stringify(m.id+'-v'+variant)+']='+JSON.stringify(d)+';');const row=review.rows.find(a=>a.id===m.id&&a.variant===variant);row.surfaceTestimonyRestoration=moves;row.interactionApproaches=m.interactionApproaches;row.playerReviewViews=m.playerReviewViews;records.push({id:m.id,variant,moves});
 }
 const crossLayer=[];for(const f of fs.readdirSync(path.join(plan,'preview/prefabs7')).filter(f=>f.endsWith('.js'))){const m=load(path.join(plan,'preview/prefabs7',f),7).metadata;if(m.id==='subsided_factory')continue;const old=prior.find(a=>a.id===m.id&&a.variant===m.variant);for(const n of m.nodes){const a=old.nodes.find(a=>a.id===n.id);if(a&&Math.abs(n.y-a.y)>8)crossLayer.push({id:m.id,variant:m.variant,node:n.id,old:point(a),now:point(n)});}}
 const report={pass:crossLayer.length===0,historicalRelocations:190,historicalMisassignedLayers:19,closedRoyalEntry:1,closedSurfaceTestimony:18,remainingCrossLayer:crossLayer,records,limits:'离线体素DDA与整块AABB证据，不等于实机寻路体验通过'};fs.writeFileSync(path.join(root,'temp/structure-design-surface-testimony.json'),JSON.stringify(report,null,2)+'\n');fs.writeFileSync(reviewFile,JSON.stringify(review,null,2)+'\n');fs.appendFileSync(path.join(dest,'structure-review.md'),'\n历史190处节点迁位经原config逐身份复核，19处跨层误归属已关闭：王庭1处按用户要求移至螺旋起点；fiction 6种×3变体信物恢复原地面环形碑位y4。非工厂 |ΔY|>8 剩余0。\n');console.log(JSON.stringify({pass:report.pass,restored:18,remainingCrossLayer:crossLayer}));process.exit(report.pass?0:1);
}
if(mode==='royal-entry'){
 const file=path.join(plan,'preview/prefabs7/forgotten_lake_court-v0.js'),d=load(file,7),m=d.metadata,cells=decode(d.voxel),node=m.nodes.find(n=>n.id==='entrance-story-board'),from=point(node),to=[136,4,125],feet=[136,4,126],eye=[136.5,5.62,126.5],target=to.map(v=>v+.5),material='gtsr:draft_notice_board#0';
 if(cells.has(key(to))||cells.has(key([136,5,125]))||cells.has(key(feet))||cells.has(key([136,5,126]))||!natural(cells.get(key([136,3,125])))||!natural(cells.get(key([136,3,126]))))throw new Error('legacy spiral start clearance/support mismatch');
 if(cells.get(key(from))!==material)throw new Error('old entrance material mismatch');
 cells.delete(key(from));cells.set(key(to),material);
 if(!clearVoxelRay(cells,eye,target))throw new Error('legacy spiral start board ray blocked');
 function sync(value){if(Array.isArray(value)){value.forEach(sync);return;}if(!value||typeof value!=='object')return;if(value.id===node.id&&'x'in value){[value.x,value.y,value.z]=to;}Object.values(value).forEach(sync);}sync(m);
 const proof={node:node.id,role:node.role,target,targetBlock:material,feet,eye,floor:{at:[136,3,126],material:cells.get('136,3,126')},distance:Math.hypot(...eye.map((v,i)=>v-target[i])),headClearance:true,rayUnobstructed:true};
 m.interactionApproaches=m.interactionApproaches.map(a=>a.node===node.id?proof:a);
 for(const v of m.playerReviewViews)if(v.id==='entrance'){v.eye=eye;v.target=target;v.floor=proof.floor;v.headClearance={feet,head:[136,5,126],clear:true};v.lineOfSight='clear';v.targetId=node.id;}
 const evidence={id:m.id,variant:0,node:node.id,original:[156,5,24],misplaced:from,corrected:to,originalSurfaceEntrance:null,legacyOwner:'ForgottenLakeEncounterStructure.placeCourtV3',sourceTreeCenter:[160,3,152],legacyAnchorOffset:[-24,1,-27],legacyFeetOffset:[-24,1,-26],legacyStep:0,legacyDirection:'沿北侧木台向东，每16格升1格',reason:'原低层牌仅按XZ投影匹配132高枝台；依用户指令改至原螺旋起点外侧，保留4宽木台剩余3格净通道',proof,productionConstraint:'仅在实际legacy木台已生成后以ax/az/y0偏移绑定此牌；不可用treeOverlay受冠高钳制的anchorY，也不得改动天然木台',sources:['plan/临时计划/preview/revision3.js:146','src/main/java/com/miaokatze/gtsr/common/dimension/prosperity/encounter/ForgottenLakeEncounterStructure.java:412']};
 m.legacyEntranceBinding={node:node.id,owner:evidence.legacyOwner,anchorOffset:evidence.legacyAnchorOffset,feetOffset:evidence.legacyFeetOffset,sourceTreeCenter:evidence.sourceTreeCenter,sourceAt:to,naturalOwner:true};m.structureDesignReview.royalEntrance=evidence;
 m.structureDesignReview.explicitAir=[...m.structureDesignReview.explicitAir.filter(p=>key(p)!==key(to)),from];
 d.voxel=pack(cells);fs.writeFileSync(file,'window.REMASTER_PREFAB7_DATA=window.REMASTER_PREFAB7_DATA||{};window.REMASTER_PREFAB7_DATA["forgotten_lake_court-v0"]='+JSON.stringify(d)+';');
 const prior=JSON.parse(fs.readFileSync(path.join(plan,'config/revision7-structure-plan.json'),'utf8')),crossLayer=[];
 for(const f of fs.readdirSync(path.join(plan,'preview/prefabs7')).filter(f=>f.endsWith('.js'))){const current=load(path.join(plan,'preview/prefabs7',f),7).metadata;if(current.id==='subsided_factory')continue;const old=prior.find(a=>a.id===current.id&&a.variant===current.variant);for(const n of current.nodes){const a=old.nodes.find(a=>a.id===n.id);if(a&&Math.abs(n.y-a.y)>8)crossLayer.push({id:current.id,variant:current.variant,node:n.id,role:n.role,old:point(a),now:point(n),review:'需按原台座地面/房间职责审查，不以最新moves为空代替历史审计'});}}
 const report={pass:true,evidence,crossLayer};fs.writeFileSync(path.join(root,'temp/structure-design-royal-entry.json'),JSON.stringify(report,null,2)+'\n');
 const reviewFile=path.join(dest,'structure-review.json'),review=JSON.parse(fs.readFileSync(reviewFile,'utf8')),row=review.rows.find(r=>r.id===m.id&&r.variant===0);row.royalEntrance=evidence;row.interactionApproaches=m.interactionApproaches;row.playerReviewViews=m.playerReviewViews;fs.writeFileSync(reviewFile,JSON.stringify(review,null,2)+'\n');fs.appendFileSync(path.join(dest,'structure-review.md'),'\n王庭入口牌已由误迁枝台[156,134,24]定向移至原螺旋第0步外侧[136,4,125]。旧source树心[160,3,152]；实际legacy绑定必须为[ax-24,y0+1,az-27]，保4宽木台剩余3格净通道；未改天然木叶。\n');
 console.log(JSON.stringify({pass:true,from,to,proof,crossLayerCount:crossLayer.length}));process.exit(0);
}
if(mode==='interaction'){
 const records=[],errors=[];
 for(const file of fs.readdirSync(path.join(plan,'preview/prefabs7')).filter(n=>n.endsWith('.js')).sort()){
  const d=load(path.join(plan,'preview/prefabs7',file),7),m=d.metadata,cells=decode(d.voxel),get=p=>cells.get(key(p));
  const actors=p=>(m.spawns||[]).some(n=>{const c=n.clearance||{width:3,depth:3,height:3};return Math.abs(p[0]-n.x)<c.width/2+.5&&Math.abs(p[2]-n.z)<c.depth/2+.5&&p[1]<n.y+c.height&&p[1]+2>n.y;});
  const stand=p=>{const f=get([p[0],p[1]-1,p[2]]);return(solid(f)||natural(f))&&!get(p)&&!get([p[0],p[1]+1,p[2]])&&!actors(p);};
  function visible(n){const target=point(n);if(!get(target))return null;for(let r=1;r<=7;r++)for(let dx=-r;dx<=r;dx++)for(let dz=-r;dz<=r;dz++){if(Math.max(Math.abs(dx),Math.abs(dz))!==r)continue;for(const dy of [0,-1,1,-2,2,-3,3]){const feet=[target[0]+dx,target[1]+dy,target[2]+dz];if(!stand(feet))continue;const eye=[feet[0]+.5,feet[1]+1.62,feet[2]+.5],aim=target.map(n=>n+.5),distance=Math.hypot(...eye.map((v,i)=>v-aim[i]));if(distance>8)continue;if(clearVoxelRay(cells,eye,aim))return{node:n.id,role:n.role,target:aim,targetBlock:get(target),feet,eye,floor:{at:[feet[0],feet[1]-1,feet[2]],material:get([feet[0],feet[1]-1,feet[2]])},distance:Math.round(distance*1000)/1000,headClearance:true,rayUnobstructed:true};}}return null;}
  const mechanismCells=new Set((m.shapeMechanisms||[]).flatMap(s=>[s.control,...s.delta.map(v=>v.at)]).map(key)),damage=new Set((m.damageManifest||[]).flatMap(d=>d.removedVoxels.map(p=>key(p.slice(0,3))))),nodes=[...(m.nodes||[]).filter(n=>['control','memory','chest','testimony','puzzle-object'].includes(n.role)),...(m.navigationHints||[])],nodeCells=new Set([...m.nodes,...(m.navigationHints||[])].map(n=>key(point(n)))),moves=[];
  function sync(id,old,p){function visit(value){if(Array.isArray(value)){for(const v of value)visit(v);return;}if(!value||typeof value!=='object')return;if(value.id===id&&'x'in value&&'y'in value&&'z'in value){value.x=p[0];value.y=p[1];value.z=p[2];}for(const v of Object.values(value))visit(v);}visit(m);for(const s of m.shapeMechanisms||[])if(s.id===id){s.control=p;for(const site of m.corridor7MechanismSites||[])if(site.compiledMechanism===id)site.position=site.position.map((v,i)=>v+p[i]-old[i]);}}
  const approaches=[];
  for(const n of nodes){let evidence=visible(n);const sharedControl=n.role==='control'&&!n.id.startsWith('shape-')&&nodes.some(a=>a.id!==n.id&&key(point(a))===key(point(n)));if(evidence&&!sharedControl){approaches.push(evidence);continue;}const old=point(n),oldMat=get(old),fallback=n.role==='control'?'gtsr:ruins_pressure_gauge#3':n.role==='testimony'?'gtsr:draft5_hush_inscription#0':n.role==='memory'?'gtsr:draft_notice_board#0':n.block;
   const movableMat=n.block||(!/slag_masonry|sootstone_tiles|verdigris_pressed_brick|cast_iron_pillar|roof_tile|mossroot_paving|royal_heartwood|Prosperity/.test(oldMat||'')&&!(sharedControl&&/actuator/.test(oldMat||''))?oldMat:null)||fallback;
   if(!movableMat){errors.push(file+': no existing authored block for '+n.id);continue;}
   const room=m.rooms.filter(r=>old[0]>=r.x&&old[0]<r.x+r.w&&old[2]>=r.z&&old[2]<r.z+r.d&&old[1]>=r.y-2&&old[1]<r.y+r.h+2).sort((a,b)=>Math.abs(old[1]-a.y-2)-Math.abs(old[1]-b.y-2))[0];
   let next=null;outer:for(let r=0;r<=10;r++)for(let dx=-r;dx<=r;dx++)for(let dz=-r;dz<=r;dz++){if(r&&Math.max(Math.abs(dx),Math.abs(dz))!==r)continue;const ys=[room?.y+2,old[1]-1,old[1]+1,old[1],old[1]+2,old[1]-2].filter(Number.isFinite);for(const y of [...new Set(ys)]){const p=[old[0]+dx,y,old[2]+dz],k=key(p),foot=get([p[0],p[1]-1,p[2]]),treeSupport=m.id==='forgotten_lake_court'&&natural(foot);if(room&&(p[0]<=room.x||p[0]>=room.x+room.w-1||p[2]<=room.z||p[2]>=room.z+room.d-1||p[1]<room.y+2||p[1]>=room.y+room.h))continue;if(get(p)||nodeCells.has(k)||mechanismCells.has(k)||damage.has(k)||actors(p)||!solid(foot)&&!treeSupport)continue;cells.set(k,movableMat);const proof=visible({...n,x:p[0],y:p[1],z:p[2]});if(proof){next={p,proof};break outer;}cells.delete(k);}}
   if(!next){errors.push(file+': no protected-safe visible approach '+n.id);continue;}
   const canRemoveOld=oldMat===movableMat&&!mechanismCells.has(key(old))&&!nodes.some(a=>a.id!==n.id&&key(point(a))===key(old))&&!/slag_masonry|sootstone_tiles|verdigris_pressed_brick|cast_iron_pillar|roof_tile|mossroot_paving|royal_heartwood|Prosperity/.test(oldMat||'');
   if(canRemoveOld){cells.delete(key(old));m.structureDesignReview.explicitAir.push(old);}sync(n.id,old,next.p);nodeCells.delete(key(old));nodeCells.add(key(next.p));moves.push({id:n.id,role:n.role,from:old,to:next.p,material:movableMat,removedOld:canRemoveOld,keptIdentity:true});approaches.push(next.proof);
  }
  m.interactionApproaches=approaches;m.interactionApproachCoverage={required:nodes.length,verified:approaches.length,missing:nodes.length-approaches.length,reach:8,method:'实体支承+两格人体净空+不占演员AABB+眼高无遮挡射线'};m.structureDesignReview.interactionRelocations=moves;
  if(m.navigationHints?.length)m.navigationHintCoverage={...(m.navigationHintCoverage||{}),required:m.navigationHints.length,verified:m.navigationHints.filter(n=>approaches.some(a=>a.node===n.id)).length,missing:m.navigationHints.filter(n=>!approaches.some(a=>a.node===n.id)).length};
  // Camera targets follow stable object identity after an actual relocation.
  for(const v of m.playerReviewViews||[]){const n=[...m.nodes,...(m.navigationHints||[])].find(n=>n.id===v.targetId),proof=n&&approaches.find(a=>a.node===n.id);if(proof&&['entrance','control','loot','route-hint'].some(k=>v.id===k||v.id.startsWith(k+'-'))){v.eye=proof.eye;v.target=proof.target;v.floor=proof.floor;v.headClearance={feet:proof.feet,head:[proof.feet[0],proof.feet[1]+1,proof.feet[2]],clear:true};v.lineOfSight='clear';}}
  // These author fixture arrays had no scalar y property; map their original local coordinates explicitly.
  if(m.factoryDepthFit){const knots=m.factoryDepthFit.knots,mapY=y=>{if(y>=0)return y;if(y<=knots[0][0])return y+48;for(let i=1;i<knots.length;i++){const[a,b]=knots[i-1],[c,e]=knots[i];if(y<=c)return Math.round(b+(y-a)*(e-b)/(c-a));}return y;};if(!m.factoryDepthFit.fixtureArraysMapped){for(const c of m.pollutionClusters||[])c.positions=c.positions.map(p=>[p[0],mapY(p[1]),p[2]]);for(const r of m.rooms)if(r.interior?.corridor7Fixtures)r.interior.corridor7Fixtures=r.interior.corridor7Fixtures.map(p=>[p[0],mapY(p[1]),p[2]]);m.factoryDepthFit.fixtureArraysMapped=true;}}
  d.voxel=pack(cells);const k=m.id+'-v'+m.variant;fs.writeFileSync(path.join(plan,'preview/prefabs7',file),'window.REMASTER_PREFAB7_DATA=window.REMASTER_PREFAB7_DATA||{};window.REMASTER_PREFAB7_DATA['+JSON.stringify(k)+']='+JSON.stringify(d)+';');records.push({id:m.id,variant:m.variant,coverage:m.interactionApproachCoverage,moves,approaches});
 }
 const report={pass:!errors.length,structures:new Set(records.map(r=>r.id)).size,variants:records.length,verified:records.reduce((n,r)=>n+r.coverage.verified,0),missing:records.reduce((n,r)=>n+r.coverage.missing,0),moved:records.reduce((n,r)=>n+r.moves.length,0),errors,records,limits:'离线眼高射线与体素人体净空，不替代MC专用形状raytrace/寻路/多人实机验证'};
 fs.writeFileSync(path.join(root,'temp/structure-design-interactions.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({pass:report.pass,structures:report.structures,variants:report.variants,verified:report.verified,missing:report.missing,moved:report.moved,errors:errors.slice(0,20),errorCount:errors.length}));process.exit(report.pass?0:1);
}
if(mode==='verify'){
 const prior=JSON.parse(fs.readFileSync(path.join(plan,'config/revision7-structure-plan.json'),'utf8')),errors=[],records=[];
 for(const file of fs.readdirSync(path.join(plan,'preview/prefabs7')).filter(n=>n.endsWith('.js')).sort()){
  const d=load(path.join(plan,'preview/prefabs7',file),7),m=d.metadata,cells=decode(d.voxel),old=prior.find(r=>r.id===m.id&&r.variant===m.variant),get=p=>cells.get(key(p)),fail=x=>errors.push(file+': '+x);
  if(!old)fail('missing original ID/variant');
  if(cells.size!==d.voxel.count)fail('duplicate cells/count mismatch');
  const oldNodes=new Map((old?.nodes||[]).map(n=>[n.id,n]));for(const n of m.nodes){const a=oldNodes.get(n.id);if(!a||['role','code','reference','target','completion'].some(k=>a[k]!==n[k]))fail('changed node identity/gate '+n.id);if(a&&m.id!=='subsided_factory'&&Math.abs(n.y-a.y)>8)fail('historical cross-layer node relocation '+n.id);}
  if(m.nodes.length!==old.nodes.length)fail('node count changed');
  for(let i=0;i<m.rooms.length;i++){const r=m.rooms[i],a=old.rooms[i];if(!a||r.moduleId!==a.moduleId||r.w!==a.w||r.h!==a.h||r.d!==a.d)fail('room identity/clearance changed');}
  for(const s of m.shapeMechanisms){if(!get(s.control))fail('missing control '+s.id);for(const delta of s.delta)if(delta.closed===null?get(delta.at):get(delta.at)!==delta.closed)fail('changed closed mechanism '+s.id+' '+delta.at);}
  for(const n of m.spawns){const c=n.clearance;if(!c)continue;for(let x=n.x-(c.width-1)/2;x<=n.x+(c.width-1)/2;x++)for(let z=n.z-(c.depth-1)/2;z<=n.z+(c.depth-1)/2;z++){if(c.mode!=='aerial'&&!get([x,n.y-1,z]))fail('actor support '+n.id);for(let y=n.y;y<n.y+c.height;y++)if(get([x,y,z]))fail('actor clearance '+n.id);}}
  for(const a of m.damageManifest||[])for(const p of a.removedVoxels||[])if(get(p.slice(0,3)))fail('accident gap filled');
  const interactive=[...m.nodes.filter(n=>['control','memory','chest','testimony','puzzle-object'].includes(n.role)),...(m.navigationHints||[])];
  for(const n of interactive){const a=m.interactionApproaches?.find(a=>a.node===n.id);if(!a||a.distance>8||!a.rayUnobstructed||!get(point(n)))fail('missing visible interactive approach '+n.id);else{if(!get(a.floor.at)||get(a.feet)||get([a.feet[0],a.feet[1]+1,a.feet[2]]))fail('interaction stand obstructed '+n.id);const target=point(n).map(v=>v+.5);if(!clearVoxelRay(cells,a.eye,target))fail('interaction ray obstructed '+n.id);}}
  for(const n of m.navigationHints||[]){if(!n.navigationHint||n.role!=='memory'||get(point(n))!==n.block||!n.readOnly||!n.guideTarget?.length)fail('navigation hint contract '+n.id);if(m.nodes.some(a=>key(point(a))===key(point(n))))fail('navigation hint overwrites original node '+n.id);}
  if(!m.playerReviewViews?.some(v=>v.id==='entrance'))fail('missing eye-level entrance');
  for(const v of m.playerReviewViews||[]){if(!get(v.floor.at))fail('camera floor absent '+v.id);if(get(v.headClearance.feet)||get(v.headClearance.head))fail('camera body obstructed '+v.id);}
  if(m.id==='forgotten_lake_court'){const d6=load(path.join(plan,'preview/prefabs6',file),6);for(const[k,mat]of decode(d6.voxel))if(natural(mat)&&cells.get(k)!==mat)fail('natural tree changed');}
  if(m.id==='subsided_factory'&&(!m.factoryDepthFit||m.factoryDepthFit.newMinY!==-118||m.rooms.length!==30||m.rooms[16].h!==24||m.terrain.cover!==8||m.terrain.highestBuildingY!==Math.max(...m.rooms.map(r=>r.y+r.h+1))))fail('factory layer contract');
  records.push({id:m.id,variant:m.variant,views:m.playerReviewViews?.length||0,absentViews:m.playerReviewAbsentViews||[],nodeIdentities:m.nodes.length,rooms:m.rooms.length,factoryDepthFit:m.factoryDepthFit||null});
 }
 const report={pass:errors.length===0&&records.length===268,structures:new Set(records.map(r=>r.id)).size,variants:records.length,errors,records,limits:'静态体素/存档身份/眼高净空核验，不等于完整MC碰撞、寻路、光效或实机审美'};
 fs.writeFileSync(path.join(root,'temp/structure-design-verification.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({pass:report.pass,structures:report.structures,variants:report.variants,errors:report.errors.slice(0,24),errorCount:report.errors.length}));process.exit(report.pass?0:1);
}
fs.mkdirSync(dest,{recursive:true});const files=fs.readdirSync(path.join(plan,'preview/prefabs7')).filter(n=>n.endsWith('.js')&&(!filter||n.includes(filter))).sort();
const profilePath=path.join(__dirname,'structure_design_profiles.json');let profiles=fs.existsSync(profilePath)?JSON.parse(fs.readFileSync(profilePath,'utf8')):null;
if(!profiles){profiles={schema:1,source:'revision7 original per-ID author contracts',structures:{}};for(const file of files){const d=load(path.join(plan,'preview/prefabs7',file),7);if(d.metadata.variant===0)profiles.structures[d.metadata.id]=makeProfile(d.metadata);}fs.writeFileSync(profilePath,JSON.stringify(profiles,null,2)+'\n');}
const previousPath=path.join(dest,'structure-review.json'),previous=mode==='apply'&&fs.existsSync(previousPath)?JSON.parse(fs.readFileSync(previousPath,'utf8')).rows:[];
const rows=[];for(const file of files){const d=load(path.join(plan,'preview/prefabs7',file),7),oldPath=path.join(plan,'preview/prefabs6',file),old=fs.existsSync(oldPath)?load(oldPath,6):null;if(mode==='apply')fitFactory(d);const priorAuthor=d.metadata.structureDesignReview;const report=refine(d,old,mode==='apply',profiles.structures[d.metadata.id]);const prior=previous.find(r=>r.id===report.id&&r.variant===report.variant);if(prior){report.before=prior.before;const logged=new Set(prior.removed.map(r=>key(r.at)));const recovered=(priorAuthor?.explicitAir||[]).filter(p=>!logged.has(key(p))).map(p=>({at:p,material:'author-stair-deck-or-corridor',why:'先前已写快照的定向修整，按累计explicitAir恢复回执'}));for(const k of ['removed','added','interactionRepairs','detailGroups'])report[k]=[...prior[k],...report[k]];report.removed.push(...recovered);if(priorAuthor?.detailGroups?.length>report.detailGroups.length)report.detailGroups=priorAuthor.detailGroups;d.metadata.structureDesignReview.explicitAir=report.removed.map(r=>r.at);d.metadata.structureDesignReview.detailGroups=report.detailGroups;}
 if(mode==='apply'){const k=d.metadata.id+'-v'+d.metadata.variant,body='window.REMASTER_PREFAB7_DATA=window.REMASTER_PREFAB7_DATA||{};window.REMASTER_PREFAB7_DATA['+JSON.stringify(k)+']='+JSON.stringify(d)+';';fs.writeFileSync(path.join(plan,'preview/prefabs7',file),body);report.sha256=crypto.createHash('sha256').update(body).digest('hex');}rows.push(report);if(rows.length%25===0)console.log(mode+': '+rows.length+'/'+files.length);}
const total=field=>rows.reduce((n,r)=>n+field(r),0),report={schema:1,mode,structures:new Set(rows.map(r=>r.id)).size,variants:rows.length,summary:{removed:total(r=>r.removed.length),added:total(r=>r.added.length),beforeRouteSolidSamples:total(r=>r.before.routeSolidSamples),afterRouteSolidSamples:total(r=>r.after.routeSolidSamples),beforeNodesWithoutApproach:total(r=>r.before.nodesWithoutApproach),afterNodesWithoutApproach:total(r=>r.after.nodesWithoutApproach),deepEntranceFill:total(r=>r.before.deepEntranceFill),interactionRepairs:total(r=>r.interactionRepairs.length),detailGroups:total(r=>r.detailGroups.length),cameras:total(r=>r.cameras.length),actorViolations:total(r=>r.after.actorViolations),preservationViolations:total(r=>Object.values(r.preserved).reduce((a,b)=>a+b,0))},rows};
fs.writeFileSync(mode==='apply'?path.join(dest,'structure-review.json'):path.join(root,'temp/structure-design-baseline.json'),JSON.stringify(report,null,2)+'\n');
const md=['# 逐结构作者细化核证','','所有数值为离线整数体素检查。完整游戏、实际碰撞/光效与人物局部审美仍待验证。','',JSON.stringify(report.summary),'','| ID/方案 | 母题 | 实际删除/添加 | 路线低位占用 前→后 | 无相邻操作面 前→后 | 人物眼高样本 | 保留/缺口 |','|---|---|---|---|---|---|---|',...rows.map(r=>'| '+r.id+'/'+r.variant+' | '+r.motif+' | '+r.removed.length+'/'+r.added.length+' | '+r.before.routeSolidSamples+'→'+r.after.routeSolidSamples+' | '+r.before.nodesWithoutApproach+'→'+r.after.nodesWithoutApproach+' | '+r.cameras.length+' | '+r.reviewStatus+'；余缺口'+r.shortfalls.length+' |')];
fs.writeFileSync(mode==='apply'?path.join(dest,'structure-review.md'):path.join(root,'temp/structure-design-baseline.md'),md.join('\n')+'\n');console.log(JSON.stringify({mode,structures:report.structures,variants:report.variants,...report.summary}));
