'use strict';
const fs=require('fs'),path=require('path'),vm=require('vm');
const root=path.resolve(__dirname,'../..'),dir=path.join(root,'plan/临时计划/preview/prefabs7'),out=path.join(root,'plan/implementation/20261002212217');
const apply=process.argv[2]==='apply',rollback=process.argv[2]==='rollback',previous=process.argv[2]==='rollback'?JSON.parse(fs.readFileSync(path.join(out,'stair-review.json'),'utf8')).rows:[],key=p=>p.join(','),rows=[];
const matches={slag_masonry:'slag_masonry',sootstone_tiles:'sootstone_tiles',verdigris_pressed_brick:'verdigris_pressed_brick',mossroot_paving:'mossroot_paving',rootbound_brick:'rootbound_brick',cast_iron_pillar:'cast_iron_pillar',oath_inscription:'oath_inscription',rust_riveted_plate:'riveted_plate',furnace_firebrick:'firebrick'};
const restorationProfileFile=path.join(root,'tools/prosperity/profiles/stair-floor-restorations.json');
const restorationProfiles=fs.existsSync(restorationProfileFile)?JSON.parse(fs.readFileSync(restorationProfileFile,'utf8')).rows:[];
function stair(m,meta){if(/stairs#/.test(m))return m.split('#')[0]+'#'+meta;let a=/^gtsr:ruins_([^#]+)#/.exec(m||'');if(a&&matches[a[1]])return 'gtsr:ruins_'+matches[a[1]]+'_stairs#'+meta;a=/^gtsr:royal_(heartwood|oathwood|crownwood|rootstone)#/.exec(m||'');return a?'gtsr:royal_'+a[1]+'_stairs#'+meta:null;}
for(const file of fs.readdirSync(dir).filter(f=>f.endsWith('.js')).sort()){
 const w={window:{}};vm.createContext(w);vm.runInContext(fs.readFileSync(path.join(dir,file),'utf8'),w);const d=Object.values(w.window.REMASTER_PREFAB7_DATA)[0],m=d.metadata,index=new Map(),edits=new Map(),changes=[],unresolved=[],excluded=[];
 for(const r of d.voxel.runs){let k=r[1]+','+r[2];if(!index.has(k))index.set(k,[]);index.get(k).push(r);}
 const get=p=>{let k=key(p);if(edits.has(k))return edits.get(k);for(const r of index.get(p[1]+','+p[2])||[])if(p[0]>=r[0]&&p[0]<r[0]+r[3])return d.voxel.palette[r[4]];return null;};
 const proofFloors=new Set(),protectedCells=new Set([...(m.nodes||[]).map(n=>key([n.x,n.y,n.z])),...(m.damageManifest||[]).flatMap(x=>(x.removedVoxels||[]).map(p=>key(p.slice(0,3)))),...(m.shapeMechanisms||[]).flatMap(x=>[x.control,...(x.delta||[]).map(d=>d.at)].filter(Boolean).map(key))]);
 for(const a of m.interactionApproaches||[]){if(a.floor?.at)proofFloors.add(key(a.floor.at));for(const q of [a.feet,a.feet&&[a.feet[0],a.feet[1]+1,a.feet[2]]])if(q)protectedCells.add(key(q));}for(const v of m.playerReviewViews||[]){if(v.floor?.at)proofFloors.add(key(v.floor.at));for(const q of [v.headClearance?.feet,v.headClearance?.head])if(q)protectedCells.add(key(q));}
 const shell=p=>(m.rooms||[]).some(r=>p[0]>=r.x&&p[0]<r.x+r.w&&p[2]>=r.z&&p[2]<r.z+r.d&&p[1]>=r.y&&p[1]<=r.y+r.h+1&&(p[0]===r.x||p[0]===r.x+r.w-1||p[2]===r.z||p[2]===r.z+r.d-1||p[1]>=r.y+r.h-1));
 const bossAt=p=>(m.bossProtectedVolumes||[]).some(b=>p.every((v,i)=>v>=b.min[i]&&v<=b.max[i]));
 const protectedAt=p=>protectedCells.has(key(p))||(m.spawns||[]).some(n=>{let c=n.clearance||{width:3,depth:3,height:3};return Math.abs(p[0]-n.x)<c.width/2+.5&&Math.abs(p[2]-n.z)<c.depth/2+.5&&p[1]>=n.y&&p[1]<n.y+c.height;});
 const protectedRemoval=p=>protectedAt(p)||bossAt(p)||proofFloors.has(key(p))||(m.spawns||[]).some(n=>{let c=n.clearance||{width:3,depth:3};return p[1]===n.y-1&&Math.abs(p[0]-n.x)<c.width/2+.5&&Math.abs(p[2]-n.z)<c.depth/2+.5;});
 const routes=(m.stairRoutes||[]).map((r,i)=>({...r,key:'stairRoutes:'+i}));for(const [i,p]of(m.routes||[]).entries())if(!routes.some(r=>JSON.stringify(r.points)===JSON.stringify(p)))routes.push({points:p,width:5,key:'routes:'+i});
 // Reproduce the pinned, finite F-floor repairs without depending on a later temporary audit.
 if(!rollback)for(const profile of restorationProfiles.filter(r=>r.id===m.id&&r.variant===m.variant))for(const cell of profile.cells){
  if(get(cell.at)||protectedAt(cell.at)||bossAt(cell.at)||shell(cell.at))continue;
  if(!stair(cell.after,0)||/stairs#/.test(cell.after))throw Error('Restoration profile must contain matching full walking floor');
  edits.set(key(cell.at),cell.after);changes.push({...cell,before:null,reason:'pinned authored floor repair: '+cell.reason});
 }
 // Recover only the documented authored entrance cross sections removed by old column cleanup.
 if(m.entranceLogic7?.points&&m.terrain?.buried==='full'&&m.id!=='subsided_factory')for(const r of routes.filter(r=>r.task==='r7-door-to-door'&&JSON.stringify(r.points)===JSON.stringify(m.entranceLogic7.points)))for(let j=1;j<r.points.length;j++){const a=r.points[j-1],b=r.points[j],n=Math.max(Math.abs(b[0]-a[0]),Math.abs(b[2]-a[2]),1),alongX=Math.abs(b[0]-a[0])>=Math.abs(b[2]-a[2]);for(let i=0;i<=n;i++){const p=a.map((v,k)=>Math.round(v+(b[k]-v)*i/n));for(let side=-Math.floor(r.width/2);side<=Math.floor(r.width/2);side++)for(const depth of [0,1]){const at=[p[0]+(alongX?0:side),p[1]-depth,p[2]+(alongX?side:0)];if(!get(at)&&!protectedAt(at)&&!bossAt(at)&&!shell(at)){const material='gtsr:ruins_slag_masonry#0';edits.set(key(at),material);changes.push({route:r.key,at,before:null,after:material,reason:'restore exact r7 entrance walking cross section removed by background-column cleanup',width:r.width,depth,clearance:2});}}}}
 const surfaceAuditFile=path.join(root,'temp/stair-inactive-classification.json');if(fs.existsSync(surfaceAuditFile)){for(const row of JSON.parse(fs.readFileSync(surfaceAuditFile,'utf8')).records.filter(r=>r.id===m.id&&r.variant===m.variant&&r.category==='primary-factory-mapped-walkfloor-erased'))for(const c of row.walkfloorRepairCandidates||[]){if(get(c.at)||protectedAt(c.at)||shell(c.at)||c.protection)continue;if([1,2].some(h=>get([c.at[0],c.at[1]+h,c.at[2]])))continue;edits.set(key(c.at),c.material);changes.push({route:row.route,at:c.at,before:null,after:c.material,reason:c.source,baselineAt:c.baselineAt,width:row.width,clearance:2});}}
 let rises=0,risingRoutes=0;
 for(const r of routes){let routeRises=0;for(let j=1;j<r.points.length;j++){
  const a=r.points[j-1],b=r.points[j],dx=b[0]-a[0],dz=b[2]-a[2],n=Math.max(Math.abs(dx),Math.abs(dz),Math.abs(b[1]-a[1]),1),alongX=Math.abs(dx)>=Math.abs(dz);let prev=a;
  for(let i=1;i<=n;i++){const p=a.map((v,k)=>Math.round(v+(b[k]-v)*i/n));if(p[1]===prev[1]){prev=p;continue;}rises++;routeRises++;const high=p[1]>prev[1]?p:prev,low=p[1]>prev[1]?prev:p,ex=high[0]-low[0],ez=high[2]-low[2];let meta=Math.abs(ex)>=Math.abs(ez)?(ex>0?0:1):(ez>0?2:3);
   for(let s=-Math.floor((r.width||5)/2);s<=Math.floor((r.width||5)/2);s++){let at=[high[0]+(alongX?0:s),high[1],high[2]+(alongX?s:0)],lower=[low[0]+(alongX?0:s),low[1],low[2]+(alongX?s:0)],before=get(at);if(!stair(before,meta)||!get(lower)){for(const offset of [-1,1,-2,2,-3,3,-4,4,-5,5,-6,6]){const candidate=[at[0],high[1]+offset,at[2]],from=[lower[0],low[1]+offset,lower[2]];if(stair(get(candidate),meta)&&stair(get(from),meta)&&[candidate,from].every(q=>[1,2].every(h=>!get([q[0],q[1]+h,q[2]])))){at=candidate;lower=from;before=get(at);break;}}}const after=stair(before,meta),above=[1,2].map(h=>[at[0],at[1]+h,at[2]]);
    if(!before){excluded.push({route:r.key,at,reason:'no authored walk floor; not infilled'});continue;}
    if(!after){excluded.push({route:r.key,at,material:before,reason:'not a registered walk floor material'});continue;}
    if(protectedAt(at)){excluded.push({route:r.key,at,material:before,reason:'protected authored cell'});continue;}
    const obstacles=above.filter(q=>get(q));let blocked=obstacles.filter(q=>protectedRemoval(q)||shell(q)||!/^gtsr:ruins_(slag_masonry|sootstone_tiles|verdigris_pressed_brick|mossroot_paving|cast_iron_pillar)#/.test(get(q)));
    if(blocked.length){unresolved.push({route:r.key,at,reason:'protected or nonstructural headroom',blocked:blocked.map(q=>({at:q,material:get(q)}))});continue;}
    if(!get(lower)){excluded.push({route:r.key,at,reason:'no adjacent low walk floor'});continue;}
    if(!ex&&!ez){unresolved.push({route:r.key,at,reason:'vertical route requires authored side landing'});continue;}
    if(ex&&ez){const corners=[[at[0],lower[1],lower[2]],[lower[0],lower[1],at[2]]];const corner=corners.find(q=>!protectedAt(q)&&(!bossAt(q)||!!get(q))&&(!get(q)||stair(get(q),0))&&[1,2].every(h=>{const head=[q[0],q[1]+h,q[2]],mat=get(head);return !mat||!protectedRemoval(head)&&!shell(head)&&mat===before&&!/stairs/.test(mat);}));if(!corner){unresolved.push({route:r.key,at,reason:'diagonal rise lacks original clear orthogonal landing'});continue;}if(!get(corner)){const material=get(lower);if(!stair(material,0)||/stairs/.test(material)){unresolved.push({route:r.key,at,reason:'diagonal landing has no matching full low floor'});continue;}edits.set(key(corner),material);changes.push({route:r.key,at:corner,before:null,after:material,rise:{low,high},reason:'single orthogonal corner landing between original adjacent floors',width:r.width||5,clearance:2});}for(const h of [1,2]){const q=[corner[0],corner[1]+h,corner[2]],mat=get(q);if(mat){edits.set(key(q),null);changes.push({route:r.key,at:q,before:mat,after:null,rise:{low,high},reason:'same-material diagonal deck overlap',clearance:2});}}meta=at[0]===corner[0]?(at[2]>corner[2]?2:3):(at[0]>corner[0]?0:1);}
    const oriented=stair(before,meta);
    if(before!==oriented){edits.set(key(at),oriented);changes.push({route:r.key,at,before,after:oriented,rise:{low,high},facing:meta,width:r.width||5,clearance:2,bossBufferExistingFloorException:bossAt(at),metadataFloorOffset:at[1]-high[1]});}
    const lip=[lower[0],at[1]+2,lower[2]],lipMat=get(lip);if(lipMat&&!protectedRemoval(lip)&&!shell(lip)&&/^gtsr:ruins_(sootstone_tiles|slag_masonry|mossroot_paving)#/.test(lipMat)){edits.set(key(lip),null);changes.push({route:r.key,at:lip,before:lipMat,after:null,rise:{low,high},reason:'two-block headroom across the rising half-step boundary',clearance:2});}
    for(const q of obstacles){const removed=get(q);edits.set(key(q),null);changes.push({route:r.key,at:q,before:removed,after:null,rise:{low,high},reason:'authored rise headroom',clearance:2});}
   }prev=p;
  }
 }if(routeRises)risingRoutes++;}
 const classifiedPath=path.join(root,'temp/stair-inactive-classification.json');if(fs.existsSync(classifiedPath)){const classified=JSON.parse(fs.readFileSync(classifiedPath,'utf8')).records.filter(x=>x.id===m.id&&x.variant===m.variant&&x.category==='actual-surface-stair-needed');for(const row of classified)for(const c of row.actualStairCandidates||[]){const at=c.at,low=c.low,before=get(at),after=stair(before,c.expectedMeta);if(!after||protectedAt(at)||!get(low)||Math.abs(at[1]-low[1])!==1||c.diagonal)continue;const head=[1,2].map(h=>[at[0],at[1]+h,at[2]]);if(head.some(q=>get(q)))continue;if(before!==after){edits.set(key(at),after);changes.push({route:row.route,at,before,after,rise:{low,high:at},facing:c.expectedMeta,width:row.width,clearance:2,reason:'independent original-surface audit: actual slope reverses or differs from metadata'});}}}
 if(rollback){const prior=previous.find(r=>r.id===m.id&&r.variant===m.variant);edits.clear();for(const c of [...(prior?.changes||[])].reverse())edits.set(key(c.at),c.before);delete m.stairSurfaceReview;}
 if((apply||rollback)&&edits.size&&m.id!=='forgotten_lake_court'){const palette=[...d.voxel.palette],pi=new Map(palette.map((v,i)=>[v,i])),runs=[];const add=(x,y,z,n,mat)=>{if(!mat)return;if(!pi.has(mat)){pi.set(mat,palette.length);palette.push(mat);}let q=runs.at(-1),id=pi.get(mat);if(q&&q[1]===y&&q[2]===z&&q[0]+q[3]===x&&q[4]===id)q[3]+=n;else runs.push([x,y,z,n,id]);};for(const [x,y,z,n,id]of d.voxel.runs){let start=x,mat=d.voxel.palette[id];for(let j=x;j<x+n;j++){const k=key([j,y,z]);if(!edits.has(k))continue;if(j>start)add(start,y,z,j-start,mat);add(j,y,z,1,edits.get(k));start=j+1;}if(start<x+n)add(start,y,z,x+n-start,mat);}for(const [k,mat]of edits){const p=k.split(',').map(Number);if(!mat)continue;let found=false;for(const r of index.get(p[1]+','+p[2])||[])if(p[0]>=r[0]&&p[0]<r[0]+r[3]){found=true;break;}if(!found)add(p[0],p[1],p[2],1,mat);}runs.sort((a,b)=>a[1]-b[1]||a[2]-b[2]||a[0]-b[0]);d.voxel={...d.voxel,palette,runs,count:runs.reduce((a,r)=>a+r[3],0)};if(!rollback)m.stairSurfaceReview={version:1,changes:changes.filter(c=>c.after).length,clearance:2,policy:'Only authored adjacent floors; preserve missing support and protected cells'};fs.writeFileSync(path.join(dir,file),'window.REMASTER_PREFAB7_DATA=window.REMASTER_PREFAB7_DATA||{};window.REMASTER_PREFAB7_DATA['+JSON.stringify(m.id+'-v'+m.variant)+']='+JSON.stringify(d)+';');}
 rows.push({id:m.id,variant:m.variant,rises,risingRoutes,changes,unresolved,excluded});
}
const totals=rows.reduce((a,r)=>{for(const k of ['rises','risingRoutes'])a[k]+=r[k];for(const k of ['changes','unresolved','excluded'])a[k]+=r[k].length;return a;},{rises:0,risingRoutes:0,changes:0,unresolved:0,excluded:0});const report={schema:1,apply,structures:new Set(rows.map(r=>r.id)).size,variants:rows.length,totals,rows};if(!rollback)fs.writeFileSync(path.join(out,'stair-review.json'),JSON.stringify(report,null,2));fs.writeFileSync(path.join(out,'stair-review.md'),'# 阶梯逐变体执行审查\n\n'+JSON.stringify(totals)+'\n\n保留无实体原地板、保护单元和未经授权的斜向/竖直路线；未决项逐格见 JSON。\n');console.log(JSON.stringify({...report,rows:undefined}));
