import java.lang.reflect.*;
import java.util.*;
import net.minecraft.block.*;
import net.minecraft.init.Blocks;
import net.minecraft.world.World;
import net.minecraft.profiler.Profiler;
import com.google.gson.*;
import com.miaokatze.gtsr.common.blocks.BlocksGTSR;
import com.miaokatze.gtsr.common.dimension.framework.structure.*;
import com.miaokatze.gtsr.common.dimension.prosperity.architecture.*;
import com.miaokatze.gtsr.common.dimension.prosperity.encounter.ForgottenLakeEncounterStructure;

/** Capture actual generator output, never the old cached legacy model. */
public class RoyalStairGeometryCheck {
 public static void main(String[] args)throws Exception{
  StairCollisionCheck.main(new String[0]);
  BlocksGTSR.prosperityJadeLeaves=new com.miaokatze.gtsr.common.dimension.prosperity.block.BlockProsperityCanopyLeaves("ProsperityJadeLeaves","gtsr:prosperity_jade_leaves_side","gtsr:prosperity_jade_leaves_top");
  StairCollisionCheck.W w=(StairCollisionCheck.W)RemasterRuntimeCheck.u.allocateInstance(StairCollisionCheck.W.class);w.blocks=new HashMap<>();w.metas=new HashMap<>();w.tiles=new HashMap<>();w.loaded=true;RemasterRuntimeCheck.set(w,World.class,"provider",RemasterRuntimeCheck.u.allocateInstance(com.miaokatze.gtsr.common.dimension.prosperity.WorldProviderProsperityRuins.class));RemasterRuntimeCheck.set(w,World.class,"theProfiler",new Profiler());RemasterRuntimeCheck.set(w,World.class,"rand",new Random(1));
  int ax=0,az=0,y0=3,trunkH=args.length>0?Integer.parseInt(args[0]):139,layout=args.length>1?Integer.parseInt(args[1]):3;
  Map<String,String> stairBefore=new HashMap<>();
  BlockSink sink=(x,y,z,raw,meta,flags)->{if(raw==null)throw new AssertionError("null production royal material");String k=w.key(x,y,z);Block block=(Block)raw;if(block instanceof net.minecraft.block.BlockStairs&&w.blocks.get(k)==BlocksGTSR.prosperityZenithLog)stairBefore.put(k,"gtsr:ProsperityZenithLog#"+w.metas.get(k));if(block==Blocks.air){w.blocks.remove(k);w.metas.remove(k);}else{w.blocks.put(k,block);w.metas.put(k,meta);}return true;};
  StructureBuilder builder=new StructureBuilder(sink);if(layout==3)ForgottenLakeEncounterStructure.placeInto(null,builder,ax,az,y0,trunkH);else{BlocksGTSR.ruinedCasing=new com.miaokatze.gtsr.common.dimension.prosperity.block.BlockRuinedCasing();Constructor<BlockPane> bars=BlockPane.class.getDeclaredConstructor(String.class,String.class,net.minecraft.block.material.Material.class,boolean.class);bars.setAccessible(true);RemasterRuntimeCheck.setBlock("iron_bars",bars.newInstance("iron_bars","iron_bars",net.minecraft.block.material.Material.iron,true));Method old=ForgottenLakeEncounterStructure.class.getDeclaredMethod(layout==1?"placeLegacyInto":"placeV2Into",World.class,StructureBuilder.class,int.class,int.class,int.class,int.class);old.setAccessible(true);old.invoke(null,null,builder,ax,az,y0,trunkH);}
  Map<Block,String> ids=new IdentityHashMap<>();if(layout<3){ids.put(BlocksGTSR.ruinedCasing,"gtsr:RuinedCasing");ids.put(Blocks.iron_bars,"minecraft:iron_bars");}ids.put(BlocksGTSR.prosperityZenithLog,"gtsr:ProsperityZenithLog");ids.put(BlocksGTSR.prosperityJadeLeaves,"gtsr:ProsperityJadeLeaves");for(Map.Entry<String,Block> e:RoyalArchitecture.BLOCKS.entrySet())ids.put(e.getValue(),"gtsr:royal_"+e.getKey());
  List<String> palette=new ArrayList<>();Map<String,Integer> pi=new HashMap<>();List<int[]> points=new ArrayList<>();for(String k:w.blocks.keySet()){String[] s=k.split(",");String id=ids.get(w.blocks.get(k));if(id==null)throw new AssertionError("unmapped actual royal block "+w.blocks.get(k));String material=id+"#"+w.metas.get(k);if(!pi.containsKey(material)){pi.put(material,palette.size());palette.add(material);}points.add(new int[]{Integer.parseInt(s[0]),Integer.parseInt(s[1]),Integer.parseInt(s[2]),pi.get(material)});}points.sort(Comparator.<int[]>comparingInt(p->p[1]).thenComparingInt(p->p[2]).thenComparingInt(p->p[0]));List<int[]> runs=new ArrayList<>();for(int[] p:points){int[] r=runs.isEmpty()?null:runs.get(runs.size()-1);if(r!=null&&r[1]==p[1]&&r[2]==p[2]&&r[0]+r[3]==p[0]&&r[4]==p[3])r[3]++;else runs.add(new int[]{p[0],p[1],p[2],1,p[3]});}
  JsonObject out=new JsonObject();Gson gson=new GsonBuilder().serializeNulls().create();out.addProperty("id","forgotten_lake_court_live_stairs");out.addProperty("layoutVersion",layout);out.addProperty("seed",0);out.addProperty("ax",ax);out.addProperty("az",az);out.addProperty("y0",y0);out.addProperty("trunkH",trunkH);out.addProperty("count",points.size());out.add("palette",gson.toJsonTree(palette));out.add("runs",gson.toJsonTree(runs));
  java.nio.file.Files.write(java.nio.file.Paths.get(layout==3&&trunkH==139?"temp/royal-stair-geometry.json":"temp/royal-stair-geometry-layout"+layout+"-h"+trunkH+".json"),gson.toJson(out).getBytes(java.nio.charset.StandardCharsets.UTF_8));
  int pass=0,fail=0;List<String> errors=new ArrayList<>();int top=y0+trunkH+2,steps=(top-y0)*(layout==3?16:8)+(layout==3?15:7),riseRun=layout==3?16:8;for(int s=riseRun;s<=steps;s+=riseRun){int[] a=spiral(s-1,y0,layout),b=spiral(s,y0,layout);StairCollisionCheck.E e=new StairCollisionCheck.E(w);e.setPosition(a[0]+.5,a[1]+1,a[2]+.5);e.onGround=true;if(!w.getCollidingBoundingBoxes(e,e.boundingBox).isEmpty()){errors.add("spiral occupied low "+s);fail++;continue;}StairCollisionCheck.move(e,b[0]+.5,b[2]+.5);if(Math.abs(e.posX-b[0]-.5)<.1&&Math.abs(e.posZ-b[2]-.5)<.1&&e.boundingBox.minY>=b[1]+.95&&descend(w,b,a))pass++;else{fail++;errors.add("spiral blocked "+s+" feet="+e.boundingBox.minY);}}
  int branchPass=0,branchFail=0,connectorPass=0,connectorFail=0;
  for(int room=0;layout==3&&room<8;room++){List<int[]> route=branch(ax,az,y0,trunkH,room);for(int i=1;i<route.size();i++){int[] a=route.get(i-1),c=route.get(i);if(a[1]==c[1])continue;int[] low=a[1]<c[1]?a:c,high=a[1]<c[1]?c:a;if(walk(w,low,high,7)&&descend(w,high,low,7))branchPass++;else{branchFail++;errors.add("branch "+room+" rise "+i+" "+Arrays.toString(low)+" -> "+Arrays.toString(high));}}}
  if(layout<3)for(int room=0;room<4;room++){int[] p=layout==1?ForgottenLakeEncounterStructure.legacyPlatform(ax,az,y0,trunkH,room):ForgottenLakeEncounterStructure.platformV2(ax,az,y0,trunkH,room),offset={4,7,10,1};int baseFloor=y0+offset[room]+12*Math.floorDiv(p[1]-y0-offset[room],12);for(int j=15;j<=(layout==1?30:38);j++){int previous=Math.min(p[1],baseFloor+Math.max(0,j-(layout==1?15:16))),y=Math.min(p[1],baseFloor+Math.max(0,j-(layout==1?14:15)));if(previous==y)continue;int[] a={ax+(room==0?j-1:room==2?-(j-1):0),previous,az+(room==1?j-1:room==3?-(j-1):0)},b={ax+(room==0?j:room==2?-j:0),y,az+(room==1?j:room==3?-j:0)};if(walk(w,a,b,layout==1?3:5)&&descend(w,b,a,layout==1?3:5))branchPass++;else{branchFail++;errors.add("old branch "+room+" j="+j);}}}
  Method cf=ForgottenLakeEncounterStructure.class.getDeclaredMethod("connectorFloor",int.class,int.class,int.class,int.class,int.class);cf.setAccessible(true);int base=y0+10+12*Math.floorDiv(trunkH+2-10,12);for(int j=-54;j<=0;j++){int previous=(int)cf.invoke(null,j-1,top,base,layout==3?24:12,layout==1?3:4),y=(int)cf.invoke(null,j,top,base,layout==3?24:12,layout==1?3:4);if(previous==y)continue;int[] a={j-1,previous,0},b={j,y,0},low=previous<y?a:b,high=previous<y?b:a;if(walk(w,low,high,7)&&descend(w,high,low,7))connectorPass++;else{connectorFail++;errors.add("connector "+j);}}
  int completePassed=0,completeFailed=0;List<List<int[]>> completeRoutes=new ArrayList<>();List<int[]> spiralRoute=new ArrayList<>();for(int s=0;s<=steps;s++)spiralRoute.add(spiral(s,y0,layout));completeRoutes.add(spiralRoute);
  if(layout==3)for(int room=0;room<8;room++)completeRoutes.add(branchAccess(w,ax,az,y0,trunkH,room));
  if(layout<3)for(int room=0;room<4;room++){int[] p=layout==1?ForgottenLakeEncounterStructure.legacyPlatform(ax,az,y0,trunkH,room):ForgottenLakeEncounterStructure.platformV2(ax,az,y0,trunkH,room),offset={4,7,10,1};int bf=y0+offset[room]+12*Math.floorDiv(p[1]-y0-offset[room],12);List<int[]> oldRoute=new ArrayList<>();for(int j=12;j<=(layout==1?30:38);j++)oldRoute.add(new int[]{ax+(room==0?j:room==2?-j:0),Math.min(p[1],bf+Math.max(0,j-(layout==1?14:15))),az+(room==1?j:room==3?-j:0)});completeRoutes.add(oldRoute);}
  List<int[]> connectorRoute=new ArrayList<>();for(int j=-55;j<=0;j++)connectorRoute.add(new int[]{j,(int)cf.invoke(null,j,top,base,layout==3?24:12,layout==1?3:4),0});completeRoutes.add(connectorRoute);
  for(int i=0;i<completeRoutes.size();i++){List<int[]> route=completeRoutes.get(i);int width=i==0?1:layout<3&&i<completeRoutes.size()-1?(layout==1?3:5):7;boolean f=StairCollisionCheck.continuousRoute(w,route,width);Collections.reverse(route);boolean r=StairCollisionCheck.continuousRoute(w,route,width);Collections.reverse(route);if(f&&r)completePassed++;else{completeFailed++;errors.add("complete physical route "+i+" forward="+f+" backward="+r);}}
  List<Map<String,Object>> stairVoxels=new ArrayList<>();for(String k:w.blocks.keySet())if(w.blocks.get(k)==RoyalArchitecture.get("zenith_log_stairs")){String[] xyz=k.split(",");int x=Integer.parseInt(xyz[0]),y=Integer.parseInt(xyz[1]),z=Integer.parseInt(xyz[2]),facing=w.metas.get(k)&3;Map<String,Object> audit=new LinkedHashMap<>();audit.put("at",new int[]{x,y,z});audit.put("before",stairBefore.get(k));audit.put("after","gtsr:royal_zenith_log_stairs#"+w.metas.get(k));audit.put("facing",facing);audit.put("low",new int[]{x+(facing==0?-1:facing==1?1:0),y-1,z+(facing==2?-1:facing==3?1:0)});audit.put("clearance",2);stairVoxels.add(audit);}out.add("stairs",gson.toJsonTree(stairVoxels));
  out.add("walkRoutes",gson.toJsonTree(completeRoutes));java.nio.file.Files.write(java.nio.file.Paths.get(layout==3&&trunkH==139?"temp/royal-stair-geometry.json":"temp/royal-stair-geometry-layout"+layout+"-h"+trunkH+".json"),gson.toJson(out).getBytes(java.nio.charset.StandardCharsets.UTF_8));
  JsonObject report=new JsonObject();report.addProperty("completeBidirectionalRoutesPassed",completePassed);report.addProperty("completeBidirectionalRoutesFailed",completeFailed);report.addProperty("spiralRises",pass+fail);report.addProperty("walked",pass);report.addProperty("blocked",fail);report.addProperty("branchRises",branchPass+branchFail);report.addProperty("branchWalked",branchPass);report.addProperty("branchBlocked",branchFail);report.addProperty("connectorRises",connectorPass+connectorFail);report.addProperty("connectorWalked",connectorPass);report.addProperty("connectorBlocked",connectorFail);report.add("errors",gson.toJsonTree(errors));java.nio.file.Files.write(java.nio.file.Paths.get(layout==3&&trunkH==139?"temp/royal-stair-collision.json":"temp/royal-stair-collision-layout"+layout+"-h"+trunkH+".json"),gson.toJson(report).getBytes(java.nio.charset.StandardCharsets.UTF_8));System.out.println("actual royal output "+points.size()+" blocks; "+report);if(fail+branchFail+connectorFail+completeFailed>0)throw new AssertionError("actual royal bidirectional route failures: "+(fail+branchFail+connectorFail));
 }
 static int[] spiral(int s,int y0,int layout){int radius=layout==3?24:12,side=radius*2,t=s%(side*4),x,z;if(t<side){x=-radius+t;z=-radius;}else if(t<side*2){x=radius;z=-radius+t-side;}else if(t<side*3){x=radius-(t-side*2);z=radius;}else{x=-radius;z=radius-(t-side*3);}return new int[]{x,y0+s/(layout==3?16:8),z};}

 static boolean descend(StairCollisionCheck.W w,int[] high,int[] low){return descend(w,high,low,1);}
 static boolean descend(StairCollisionCheck.W w,int[] high,int[] low,int width){boolean alongX=Math.abs(high[0]-low[0])>=Math.abs(high[2]-low[2]);for(int side=-width/2;side<=width/2;side++){int[] h=high.clone(),l=low.clone();h[alongX?2:0]+=side;l[alongX?2:0]+=side;if(descendLane(w,h,l))return true;}return false;}
 static boolean descendLane(StairCollisionCheck.W w,int[] high,int[] low){StairCollisionCheck.E e=new StairCollisionCheck.E(w);e.setPosition(high[0]+.5,high[1]+1,high[2]+.5);e.onGround=true;if(!w.getCollidingBoundingBoxes(e,e.boundingBox).isEmpty())return false;int[][] paths=high[0]!=low[0]&&high[2]!=low[2]?new int[][]{{low[0],high[2],low[0],low[2]},{high[0],low[2],low[0],low[2]}}:new int[][]{{low[0],low[2],low[0],low[2]}};for(int[] path:paths){e.setPosition(high[0]+.5,high[1]+1,high[2]+.5);e.onGround=true;StairCollisionCheck.move(e,path[0]+.5,path[1]+.5);StairCollisionCheck.move(e,path[2]+.5,path[3]+.5);for(int i=0;i<12;i++)e.moveEntity(0,-.12,0);if(Math.abs(e.posX-low[0]-.5)<.1&&Math.abs(e.posZ-low[2]-.5)<.1&&e.boundingBox.minY>=low[1]+.5&&e.boundingBox.minY<=low[1]+1.01&&!w.getCollidingBoundingBoxes(e,net.minecraft.util.AxisAlignedBB.getBoundingBox(e.boundingBox.minX,e.boundingBox.minY-.05,e.boundingBox.minZ,e.boundingBox.maxX,e.boundingBox.minY+.01,e.boundingBox.maxZ)).isEmpty())return true;}return false;}
 static boolean walk(StairCollisionCheck.W w,int[] low,int[] high,int width){StairCollisionCheck.E e=new StairCollisionCheck.E(w);e.setPosition(low[0]+.5,low[1]+1,low[2]+.5);e.onGround=true;if(w.getCollidingBoundingBoxes(e,e.boundingBox).isEmpty()){StairCollisionCheck.move(e,high[0]+.5,high[2]+.5);if(Math.abs(e.posX-high[0]-.5)<.1&&Math.abs(e.posZ-high[2]-.5)<.1&&e.boundingBox.minY>=high[1]+.95)return true;}return StairCollisionCheck.bypass(w,low,high,width)||StairCollisionCheck.normalizedWalk(w,low,high,width,Math.abs(high[0]-low[0])>=Math.abs(high[2]-low[2]));}
 static List<int[]> branchAccess(StairCollisionCheck.W w,int ax,int az,int y0,int trunkH,int room)throws Exception{List<int[]> route=new ArrayList<>();int[] p=ForgottenLakeEncounterStructure.platform(ax,az,y0,trunkH,room);Method join=ForgottenLakeEncounterStructure.class.getDeclaredMethod("branchJoinFloor",int.class,int.class,int.class,int.class);join.setAccessible(true);for(int[] q:branch(ax,az,y0,trunkH,room)){if(Math.hypot(q[0]-p[0],q[2]-p[2])<=14)break;int[] actual=q.clone();actual[1]=(int)join.invoke(null,q[0]-ax,q[2]-az,y0,q[1]);route.add(actual);}
 Method cell=ForgottenLakeEncounterStructure.class.getDeclaredMethod("roomCellV3",int[].class,int.class,int.class,int.class);cell.setAccessible(true);for(int[] uv:new int[][]{{-17,0},{-17,-7},{-8,-7},{0,-7},{0,0}}){int[] c=(int[])cell.invoke(null,p,room,uv[0],uv[1]),dest={c[0],p[1],c[1]},start=route.get(route.size()-1);int n=Math.max(Math.abs(dest[0]-start[0]),Math.abs(dest[2]-start[2]));for(int i=1;i<=n;i++)route.add(new int[]{start[0]+(int)Math.round((dest[0]-start[0])*i/(double)n),start[1]+(int)Math.round((dest[1]-start[1])*i/(double)n),start[2]+(int)Math.round((dest[2]-start[2])*i/(double)n)});}for(int[] q:route)for(int offset:new int[]{0,-1,1,-2,2,-3,3}){int y=q[1]+offset;Block floor=w.getBlock(q[0],y,q[2]);if(!(floor instanceof net.minecraft.block.BlockStairs)&&floor!=BlocksGTSR.prosperityZenithLog)continue;StairCollisionCheck.E e=new StairCollisionCheck.E(w);e.setPosition(q[0]+.5,y+1,q[2]+.5);if(w.getCollidingBoundingBoxes(e,e.boundingBox).isEmpty()&&StairCollisionCheck.supported(w,e)){q[1]=y;break;}}return route;}
 static List<int[]> branch(int ax,int az,int y0,int trunkH,int room){int[] p=ForgottenLakeEncounterStructure.platform(ax,az,y0,trunkH,room),phase={4,6,7,9,10,0,1,3};int base=y0+phase[room]+12*Math.floorDiv(p[1]-y0-phase[room],12);double angle=room*Math.PI/4,cos=Math.cos(angle),sin=Math.sin(angle),start=room%2==0?24:Math.sqrt(1152);List<int[]> route=new ArrayList<>();for(int t=0;t<=200;t++){double u=t/200D,r=start+(112-start)*u,bend=8*Math.sin(Math.PI*u);int x=ax+(int)Math.round(cos*r-sin*bend),z=az+(int)Math.round(sin*r+cos*bend),y=base+(int)Math.round((p[1]-base)*u+2*Math.sin(Math.PI*u));if(!route.isEmpty()){int[] prev=route.get(route.size()-1);if(prev[0]==x&&prev[2]==z){prev[1]=y;continue;}if(prev[0]!=x&&prev[2]!=z)route.add(new int[]{x,prev[1],prev[2]});}route.add(new int[]{x,y,z});}return route;}

}
