'use strict';
const fs=require('fs'),path=require('path'),vm=require('vm'),crypto=require('crypto');
const root=path.resolve(__dirname,'../..'),unusedDir=path.join(root,'plan/临时计划/preview/prefabs7'),audit=JSON.parse(fs.readFileSync(path.join(root,'tools/prosperity/profiles/stair-route-baseline.json'),'utf8')),fixtures=[],inputs=[];
for(const row of audit.rows){const source=fs.readFileSync(path.join(root,row.file)),w={window:{}};inputs.push({id:row.id,variant:row.variant,file:row.file,SHA256:crypto.createHash('sha256').update(source).digest('hex')});vm.createContext(w);vm.runInContext(source.toString('utf8'),w);const d=Object.values(w.window.REMASTER_PREFAB7_DATA)[0],index=new Map();for(const r of d.voxel.runs){const k=r[1]+','+r[2];if(!index.has(k))index.set(k,[]);index.get(k).push(r);}const get=(x,y,z)=>{for(const r of index.get(y+','+z)||[])if(x>=r[0]&&x<r[0]+r[3])return d.voxel.palette[r[4]];return null;};
 for(const route of row.routeMatrix)for(const [i,t]of route.transitions.entries()){let half=Math.floor(route.width/2),alongX=Math.abs(t.high[0]-t.low[0])>=Math.abs(t.high[2]-t.low[2]),cells=[];for(let x=Math.min(t.low[0],t.high[0])-half-2;x<=Math.max(t.low[0],t.high[0])+half+2;x++)for(let z=Math.min(t.low[2],t.high[2])-half-2;z<=Math.max(t.low[2],t.high[2])+half+2;z++)for(let y=t.low[1]-7;y<=t.high[1]+7;y++){const mat=get(x,y,z);if(mat)cells.push([x,y,z,mat]);}fixtures.push({id:row.id,variant:row.variant,route:route.key,rise:i,low:t.low,high:t.high,width:route.width,alongX,cells});}
 const reviews=[...(d.metadata.structureDesignReview?.stairExceptionRoutes||[]),...(d.metadata.structureDesignReview?.stairFunctionalAccessRoutes||[])];
 for(const r of reviews){if(!r.actualPoints?.length)continue;const seen=new Set(),cells=[],half=Math.floor((r.width||5)/2)+2;for(const p of r.actualPoints)for(let x=p[0]-half;x<=p[0]+half;x++)for(let z=p[2]-half;z<=p[2]+half;z++)for(let y=p[1]-7;y<=p[1]+7;y++){const k=x+','+y+','+z;if(seen.has(k))continue;seen.add(k);const mat=get(x,y,z);if(mat)cells.push([x,y,z,mat]);}fixtures.unshift({kind:'replacement-route-proof',id:row.id,variant:row.variant,route:r.originalRouteKey,width:r.width||5,points:r.actualPoints,reason:r.reason,cells});}
}
fs.writeFileSync(path.join(root,'temp/stair-walk-fixtures.json'),JSON.stringify(fixtures));fs.writeFileSync(path.join(root,'temp/stair-walk-fixtures.inputs.json'),JSON.stringify({sourceSnapshots:inputs,fixtureSHA256:crypto.createHash('sha256').update(fs.readFileSync(path.join(root,'temp/stair-walk-fixtures.json'))).digest('hex')}));console.log(JSON.stringify({fixtures:fixtures.length,bytes:fs.statSync(path.join(root,'temp/stair-walk-fixtures.json')).size}));
