package com.miaokatze.gtsr.common.blocks;

import net.minecraft.block.material.Material;
import net.minecraft.client.renderer.texture.IIconRegister;
import net.minecraft.util.IIcon;
import net.minecraft.world.IBlockAccess;
import net.minecraftforge.fluids.BlockFluidClassic;
import net.minecraftforge.fluids.Fluid;

import com.miaokatze.gtsr.common.dimension.prosperity.biome.BiomeSanzuRiver;

import cpw.mods.fml.relauncher.Side;
import cpw.mods.fml.relauncher.SideOnly;

/**
 * 深渊执念世界侧流体方块（v1.20.40 P19 plan §I；U1 注册面）。
 * <p>
 * BlockFluidClassic（KingLemming 经典流体行为：源=meta0，流动逐级衰减，边缘自然收边；plan §I
 * 拍板"流动 tick 由 BlockFluidClassic 天然行为承担"），Material.water——桶舀取矩阵依赖此材质
 * （ItemBucket.java:88 原版舀水分支按 {@code material == Material.water && meta == 0} 判定，
 * 本方块被 FillBucketEvent handler 先手 ALLOW 短路接管，见 AbyssalFluidConversionHandler）。
 * <p>
 * <b>构造时序</b>：GT 材料流体 abyssal_obsession 于 GT preInit 末尾的 Materials.init() 回调链
 * （initMaterialProperties → mFluid → FluidRegistry，见 GTSRProsperityAirMaterials 类注释）
 * 注册；gtsr 为 required-before:gregtech，自身 preInit（BlockLoader.initBlocks）时 FluidRegistry
 * 尚不可取 ⇒ 本方块在 CommonProxy.init 段由 {@code BlockLoader.initAbyssalFluid()} 构造并注册。
 * BlockFluidBase 构造函数自身即完成 {@code fluid.setBlock(this)}（BlockFluidBase.java:60-76
 * {@code fluid.setBlock(this)}），无需也无法再手动挂接；Fluid.setBlock 二次绑定会告警
 * （Fluid.java:117-127），GT 材料管线只造 Fluid 不造世界方块（run/dimprobe-run-20260918 实测
 * 注册链无 block 挂接告警），故此处为该流体唯一 block 绑定点。
 * <p>
 * <b>两档色</b>（plan §I 拍板）：colorMultiplier 按所在群系乘色——普通水域档 0x2E5F8A、
 * 遗忘之川（BiomeSanzuRiver）档 0x142C4F 更深。贴图取流体自链贴图（GT 材质 SET_FLUID
 * autogenerated 灰度链），空回落原版 water_still/water_flow（同为灰度），色全部由本类乘色决定。
 * <p>
 * 专用服字段剥离纪律（BlockProsperityStone 同款）：@SideOnly 字段不带字段级初始化器，
 * registerBlockIcons 内赋值。
 */
public class BlockAbyssalFluid extends BlockFluidClassic {

    /** 普通水域色（RGB 乘色，plan §I 拍板）。 */
    public static final int COLOR_NORMAL = 0x2E5F8A;
    /** 遗忘之川档色（更深，plan §I 拍板）。 */
    public static final int COLOR_SANZU = 0x142C4F;

    @SideOnly(Side.CLIENT)
    private IIcon iconStill;
    @SideOnly(Side.CLIENT)
    private IIcon iconFlowing;

    public BlockAbyssalFluid(Fluid fluid) {
        super(fluid, Material.water);
        setBlockName("AbyssalFluid");
        // 源方块 meta0（worldgen 与桶装放置恒 0）；tickRate/viscosity/quanta 全走流体材质自身值
        // （BlockFluidBase.java:71 由 fluid.viscosity/200 推得），不额外覆写。
    }

    /**
     * 两档乘色（plan §I 拍板）：遗忘之川群系 → COLOR_SANZU，其余（四群系河湖）→ COLOR_NORMAL。
     * 世界渲染路径（RenderBlocks.renderBlockFluids）逐方块调用本方法取 tint。父方法
     * {@code Block.colorMultiplier(IBlockAccess,int,int,int)} 为 @SideOnly(CLIENT)
     * （Block.java:1154-1155），覆写必须同注解（专用服字段剥离纪律）。
     */
    @Override
    @SideOnly(Side.CLIENT)
    public int colorMultiplier(IBlockAccess world, int x, int y, int z) {
        return world.getBiomeGenForCoords(x, z) instanceof BiomeSanzuRiver ? COLOR_SANZU : COLOR_NORMAL;
    }

    /** 物品/粒子路径取色：普通档（群系差异化仅世界渲染承担，与原版水 getRenderColor 同口径）。 */
    @Override
    @SideOnly(Side.CLIENT)
    public int getRenderColor(int meta) {
        return COLOR_NORMAL;
    }

    /** 贴图自链：流体自带 still/flowing icon（GT 灰度 autogenerated 链）优先，空回落原版水灰度贴图。 */
    @Override
    @SideOnly(Side.CLIENT)
    public void registerBlockIcons(IIconRegister register) {
        iconStill = definedFluid != null && definedFluid.getStillIcon() != null ? definedFluid.getStillIcon()
            : register.registerIcon("water_still");
        iconFlowing = definedFluid != null && definedFluid.getFlowingIcon() != null ? definedFluid.getFlowingIcon()
            : register.registerIcon("water_flow");
    }

    @Override
    @SideOnly(Side.CLIENT)
    public IIcon getIcon(int side, int meta) {
        return meta == 0 ? iconStill : iconFlowing;
    }
}
