package com.miaokatze.gtsr.common.api.enums;

import com.miaokatze.gtsr.config.Config;

public enum MetaTileEntityID {

    // --- 单方块机器 (1+) ---
    STEAM_CACHE_NODE(1),
    REINFORCED_STEAM_CACHE_NODE(2),
    OVERPRESSURE_HUB_STORAGE_UNIT(3),
    WATER_CACHE_NODE(4),
    SINGULARITY_MINER_NODE(5),
    SINGULARITY_DRILLING_NODE(6),
    STEAM_SINGULARITY_COMPRESSOR(7),

    // --- 多方块机器 (8+) ---
    // 存储枢纽及其仓室和模块
    STEAM_HUB_ARRAY(8),
    WATER_HUB_ARRAY(9),
    STEAM_HUB_INPUT_HATCH(10),
    STEAM_HUB_OUTPUT_HATCH(11),
    WATER_HUB_INPUT_HATCH(12),
    WATER_HUB_OUTPUT_HATCH(13),
    OVERPRESSURE_TURBINE_INPUT_HATCH(14),
    HUB_STORAGE_UNIT(15),
    REINFORCED_HUB_STORAGE_UNIT(16),
    OVERPRESSURE_STEAM_CACHE_NODE(17),
    // 蒸汽生产
    LARGE_SOLAR_OVERPRESSURE_ARRAY(18),
    LARGE_GEOTHERMAL_STEAM_BOILER(19),
    // 蒸汽产电及特殊仓室
    MEGA_STEAM_TURBINE_ARRAY(20),
    // 工作机器
    STEAM_FLUID_DRILL(21),
    CRUST_STEAM_BORER(22),
    SINGULARITY_CRUST_STEAM_BORER(23),
    VEIN_STEAM_PYROLYZER(24),
    LARGE_STEAM_FURNACE(25),
    AIR_COMPRESSOR(26),
    ATMOSPHERIC_CENTRIFUGE(27),
    KINETIC_PROCESSING_ARRAY(28),
    // 特殊机器
    SINGULARITY_DRILLING_HUB(29),
    // 非典型蒸汽机
    LARGE_COKE_OVEN(30),
    SIEMENS_MARTIN_FURNACE(31),
    AMMONIA_PLANT(32),
    GEAR_STEAM_COMPRESSOR(33),

    // --- 仓室 (34+) ---
    STEAM_INPUT_HATCH_GENERIC(34),
    STEAM_OUTPUT_HATCH_GENERIC(35),
    PRESSURE_STEAM_HATCH(36),
    PRESSURE_STEAM_OUTPUT_HATCH(37),
    STEAM_OUTPUT_HATCH(38),
    STEAM_COOLING_HATCH(39),
    PRESSURE_STEAM_COOLING_HATCH(40),

    ;

    public final int ID;

    private static final int BASE = 14620;

    MetaTileEntityID(int relativeId) {
        this.ID = BASE + Config.metaIdOffset + relativeId;
    }
}
