package com.miaokatze.gtsr.common.api.enums;

import com.miaokatze.gtsr.config.Config;

public enum MetaTileEntityID {

    // --- 单方块机器 (1+) ---
    STEAM_CACHE_NODE(1),
    REINFORCED_STEAM_CACHE_NODE(2),
    WATER_CACHE_NODE(3),
    SINGULARITY_MINER_NODE(4),
    SINGULARITY_DRILLING_NODE(5),
    STEAM_SINGULARITY_COMPRESSOR(6),

    // --- 多方块机器 (7+) ---
    // 存储枢纽
    STEAM_HUB_ARRAY(7),
    WATER_HUB_ARRAY(8),
    // 蒸汽生产
    LARGE_SOLAR_OVERPRESSURE_ARRAY(9),
    LARGE_GEOTHERMAL_STEAM_BOILER(10),
    // 蒸汽产电
    MEGA_STEAM_TURBINE_ARRAY(11),
    // 工作机器
    STEAM_FLUID_DRILL(12),
    CRUST_STEAM_BORER(13),
    SINGULARITY_CRUST_STEAM_BORER(14),
    VEIN_STEAM_PYROLYZER(15),
    LARGE_STEAM_FURNACE(16),
    AIR_COMPRESSOR(17),
    ATMOSPHERIC_CENTRIFUGE(18),
    KINETIC_PROCESSING_ARRAY(19),
    // 特殊机器
    SINGULARITY_DRILLING_HUB(20),
    // 非典型蒸汽机
    LARGE_COKE_OVEN(21),
    SIEMENS_MARTIN_FURNACE(22),
    AMMONIA_PLANT(23),
    GEAR_STEAM_COMPRESSOR(24),

    // --- 仓室 (25+) ---
    STEAM_INPUT_HATCH_GENERIC(25),
    STEAM_OUTPUT_HATCH_GENERIC(26),
    PRESSURE_STEAM_HATCH(27),
    PRESSURE_STEAM_OUTPUT_HATCH(28),
    STEAM_OUTPUT_HATCH(29),
    STEAM_COOLING_HATCH(30),
    PRESSURE_STEAM_COOLING_HATCH(31),
    STEAM_HUB_INPUT_HATCH(32),
    STEAM_HUB_OUTPUT_HATCH(33),
    WATER_HUB_INPUT_HATCH(34),
    WATER_HUB_OUTPUT_HATCH(35),
    HUB_STORAGE_UNIT(38),
    REINFORCED_HUB_STORAGE_UNIT(39),
    OVERPRESSURE_STEAM_CACHE_NODE(40),
    OVERPRESSURE_TURBINE_INPUT_HATCH(41),
    OVERPRESSURE_HUB_STORAGE_UNIT(42),

    ;

    public final int ID;

    private static final int BASE = 14620;

    MetaTileEntityID(int relativeId) {
        this.ID = BASE + Config.metaIdOffset + relativeId;
    }
}
