package com.miaokatze.gtsr.common.api.enums;

import com.miaokatze.gtsr.config.Config;

public enum MetaTileEntityID {

    // --- 单方块机器 (1+) ---
    STEAM_CACHE_NODE(1),
    REINFORCED_STEAM_CACHE_NODE(2),
    OVERPRESSURE_STEAM_CACHE_NODE(3),
    WATER_CACHE_NODE(4),
    STEAM_SINGULARITY_COMPRESSOR(5),

    // --- 多方块机器 (6+) ---
    // 存储枢纽及其仓室和模块
    STEAM_HUB_ARRAY(6),
    WATER_HUB_ARRAY(7),
    STEAM_HUB_INPUT_HATCH(8),
    STEAM_HUB_OUTPUT_HATCH(9),
    WATER_HUB_INPUT_HATCH(10),
    WATER_HUB_OUTPUT_HATCH(11),
    HUB_STORAGE_UNIT(12),
    REINFORCED_HUB_STORAGE_UNIT(13),
    OVERPRESSURE_HUB_STORAGE_UNIT(14),
    // 蒸汽生产
    LARGE_SOLAR_OVERPRESSURE_ARRAY(15),
    LARGE_GEOTHERMAL_STEAM_BOILER(16),
    // 蒸汽产电及特殊仓室
    MEGA_STEAM_TURBINE_ARRAY(17),
    OVERPRESSURE_TURBINE_INPUT_HATCH(18),
    // 工作机器
    STEAM_FLUID_DRILL(19),
    CRUST_STEAM_BORER(20),
    SINGULARITY_CRUST_STEAM_BORER(21),
    VEIN_STEAM_PYROLYZER(22),
    LARGE_STEAM_FURNACE(23),
    AIR_COMPRESSOR(24),
    ATMOSPHERIC_CENTRIFUGE(25),
    KINETIC_PROCESSING_ARRAY(26),
    // 特殊机器
    SINGULARITY_DRILLING_HUB(27),
    SINGULARITY_MINER_NODE(28),
    SINGULARITY_DRILLING_NODE(29),
    // 非典型蒸汽机
    LARGE_COKE_OVEN(30),
    SIEMENS_MARTIN_FURNACE(31),
    AMMONIA_PLANT(32),
    GEAR_STEAM_COMPRESSOR(33),

    // --- 仓室 (34+) ---
    STEAM_INPUT_HATCH_GENERIC(34),
    STEAM_OUTPUT_HATCH_GENERIC(35),
    PRESSURE_STEAM_HATCH(36),
    PRESSURE_STEAM_OUTPUT_HATCH(37),
    STEAM_OUTPUT_HATCH(38),
    STEAM_COOLING_HATCH(39),
    PRESSURE_STEAM_COOLING_HATCH(40),
    // 巨型空气输入仓：仅允许空气/下界空气，容量 100,000,000 L
    MEGA_AIR_INPUT_HATCH(41),

    ;

    public final int ID;

    private static final int BASE = 14620;

    MetaTileEntityID(int relativeId) {
        this.ID = BASE + Config.metaIdOffset + relativeId;
    }
}
