package com.miaokatze.gtsr.common.dimension.prosperity.industrial;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Properties;

import net.minecraft.item.ItemStack;
import net.minecraftforge.fluids.FluidRegistry;
import net.minecraftforge.fluids.FluidStack;

import com.miaokatze.gtsr.main.GTSteamReborn;

import gregtech.api.enums.MaterialBuilder;
import gregtech.api.enums.Materials;
import gregtech.api.enums.OrePrefixes;
import gregtech.api.enums.SubTag;
import gregtech.api.enums.TextureSet;
import gregtech.api.interfaces.IMaterialHandler;
import gregtech.api.util.GTOreDictUnificator;
import gregtech.api.util.GTUtility;

/** Registered before GT Materials.init; persistent IDs protect saved dust/cell stack damage values. */
public final class ProsperityIndustrialMaterials implements IMaterialHandler {

    private static File idFile;
    private static final Map<String, Materials> MATERIALS = new LinkedHashMap<>();

    public static void configure(File file) {
        if (idFile != null && !idFile.equals(file))
            throw new IllegalStateException("Industrial ID file already configured");
        idFile = file;
    }

    @Override
    public void onMaterialsInit() {
        if (idFile == null)
            throw new IllegalStateException("Call ProsperityIndustrialMaterials.configure before GT init");
        if (!MATERIALS.isEmpty()) throw new IllegalStateException("Industrial material registration called twice");
        IndustrialMaterialColors.verifyCoverage(IndustrialRecipeLedger.get());
        Map<Integer, String> occupied = new HashMap<>();
        // values() is still empty inside this callback; the material map contains the live pre-init definitions.
        for (Materials material : Materials.getMaterialsMap()
            .values()) {
            if (material.mMetaItemSubID >= 0) occupied.put(material.mMetaItemSubID, material.mName);
        }
        Properties ids = loadIds();
        boolean firstAllocation = !idFile.exists();
        for (IndustrialRecipeLedger.MaterialDefinition definition : IndustrialRecipeLedger.get().materials) {
            if (Materials.getMaterialsMap()
                .containsKey(definition.name)) {
                throw new IllegalStateException("Industrial material name already occupied: " + definition.name);
            }
            int id;
            if (firstAllocation) {
                id = 999;
                while (id >= 0 && occupied.containsKey(id)) id--;
                if (id < 0)
                    throw new IllegalStateException("Not enough GT material IDs for prosperity industrial materials");
                ids.setProperty(definition.id, Integer.toString(id));
            } else {
                String saved = ids.getProperty(definition.id);
                if (saved == null)
                    throw new IllegalStateException("Missing persistent industrial material ID: " + definition.id);
                id = Integer.parseInt(saved);
            }
            if (id < 0 || id >= 1000 || occupied.containsKey(id)) {
                throw new IllegalStateException(
                    "Industrial material ID conflict: " + definition.id
                        + "="
                        + id
                        + " occupied by "
                        + occupied.get(id)
                        + "; keep the saved ID file and resolve the mod conflict");
            }
            occupied.put(id, definition.name);
        }
        // Save the complete mapping before creating any materials; failure cannot partially remap saved stacks.
        if (firstAllocation) saveIds(ids);
        for (IndustrialRecipeLedger.MaterialDefinition definition : IndustrialRecipeLedger.get().materials) {
            MaterialBuilder builder = new MaterialBuilder().setName(definition.name)
                .setDefaultLocalName(definition.en)
                .setARGB(IndustrialMaterialColors.getARGB(definition.id))
                .setAutoGenerateBlastFurnaceRecipes(false)
                .setAutoGeneratedVacuumFreezerRecipe(false)
                .setAutoGeneratedRecycleRecipes(false)
                .addSubTag(SubTag.NO_SMELTING)
                .addSubTag(SubTag.NO_RECYCLING)
                .addSubTag(SubTag.NO_RECYCLING_RECIPES);
            if ("dust".equals(definition.phase)) {
                builder.setIconSet(TextureSet.SET_DULL)
                    .addDustItems();
            } else {
                builder.setIconSet(TextureSet.SET_FLUID)
                    .addCell();
                if ("gas".equals(definition.phase)) builder.addGas()
                    .addSubTag(SubTag.TRANSPARENT);
                else builder.addFluid();
            }
            Materials material = builder.constructMaterial();
            material.mMetaItemSubID = Integer.parseInt(ids.getProperty(definition.id));
            MATERIALS.put(definition.id, material);
        }
        GTSteamReborn.LOG.info("[GTSR] prosperity industrial materials registered: 64 (dust=15 gas=10 fluid=39)");
    }

    private static Properties loadIds() {
        Properties ids = new Properties();
        if (idFile.exists()) {
            try (FileInputStream input = new FileInputStream(idFile)) {
                ids.load(input);
            } catch (Exception e) {
                throw new IllegalStateException("Cannot read saved industrial material IDs: " + idFile, e);
            }
        }
        return ids;
    }

    private static void saveIds(Properties ids) {
        File parent = idFile.getAbsoluteFile()
            .getParentFile();
        if (!parent.isDirectory() && !parent.mkdirs()) {
            throw new IllegalStateException("Cannot create industrial ID directory: " + parent);
        }
        File temporary = new File(parent, idFile.getName() + ".tmp");
        try (FileOutputStream output = new FileOutputStream(temporary)) {
            ids.store(output, "Persistent GT IDs. Do not delete or reallocate after creating a world.");
        } catch (Exception e) {
            throw new IllegalStateException("Cannot save industrial material IDs", e);
        }
        if (!temporary.renameTo(idFile))
            throw new IllegalStateException("Cannot install industrial material ID file: " + idFile);
    }

    public static Materials get(String id) {
        Materials material = MATERIALS.get(id);
        if (material == null) throw new IllegalStateException("Unregistered industrial material: " + id);
        return material;
    }

    public static void logRegistrationProbe() {
        auditRegistration();
    }

    public static void verifyRegistration() {
        auditRegistration();
    }

    /** Post-init live probe: actual generated dust, registered fluid and filled cell; throws on any missing form. */
    public static void auditRegistration() {
        int dust = 0, gas = 0, fluid = 0;
        for (IndustrialRecipeLedger.MaterialDefinition definition : IndustrialRecipeLedger.get().materials) {
            Materials material = get(definition.id);
            int expectedColor = IndustrialMaterialColors.getARGB(definition.id) & 0xffffff;
            int materialColor = (material.mRGBa[0] << 16) | (material.mRGBa[1] << 8) | material.mRGBa[2];
            if (materialColor != expectedColor)
                throw new IllegalStateException("Unexpected material color: " + definition.id);
            if ("dust".equals(definition.phase)) {
                ItemStack stack = GTOreDictUnificator.get(OrePrefixes.dust, material, 1L);
                if (stack == null || stack.getItem() == null)
                    throw new IllegalStateException("Missing generated dust: " + definition.id);
                dust++;
            } else {
                FluidStack stack = "gas".equals(definition.phase) ? material.getGas(1000) : material.getFluid(1000);
                ItemStack cell = GTOreDictUnificator.get(OrePrefixes.cell, material, 1L);
                FluidStack contents = GTUtility.getFluidForFilledItem(cell, true);
                if (stack == null || FluidRegistry.getFluid(definition.name) != stack.getFluid()
                    || contents == null
                    || !contents.isFluidEqual(stack)
                    || contents.amount != 1000) {
                    throw new IllegalStateException("Missing registered fluid or 1000L cell: " + definition.id);
                }
                if (stack.getFluid()
                    .getColor() != expectedColor
                    || contents.getFluid()
                        .getColor() != expectedColor)
                    throw new IllegalStateException("Unexpected fluid or filled-cell color: " + definition.id);
                if ("gas".equals(definition.phase)) gas++;
                else fluid++;
            }
            GTSteamReborn.LOG.info(
                "[GTSR] industrial material probe: " + definition.id
                    + " phase="
                    + definition.phase
                    + " meta="
                    + material.mMetaItemSubID
                    + " ok");
        }
        GTSteamReborn.LOG
            .info("[GTSR] industrial live registration audit: dust=" + dust + " gas=" + gas + " fluid=" + fluid);
    }
}
